- README.md
> chore: change Philippe Scorsolini's organization

- .github/workflows/continuous-delivery.yml
> chore: only compile the manager on every continuous delivery pipeline

- .github/workflows/chatops-receiver.yml
> fix: remove limit option in slash-command-receiver workflow

- CONTRIBUTING.md
> chore: fix dev meetings (1st/3rd Wed) and add calendar

- docs/src/cnpg-plugin.md
- internal/cmd/plugin/report/cluster.go
- internal/cmd/plugin/report/cluster_report.go
- internal/cmd/plugin/report/operator.go
- internal/cmd/plugin/report/operator_report.go
- internal/cmd/plugin/report/output.go
Closes #79 
Co-authored-by: Marco Nenciarini <marco.nenciarini@enterprisedb.com>
> fix(plugin): get the time only once to avoid directory time != zip time

- internal/cmd/plugin/report/deployments/deployments.go
- internal/cmd/plugin/report/logs.go
- internal/cmd/plugin/report/operator_report.go
The command now properly handles multiple replicas without returning an error
Closes #69
> fix: cnp report operator correctly handles multiple replicas operator deployments

- controllers/backup_controller.go
> fix: wrong ClusterName property used

- .wordlist-en-custom.txt
- README.md
- docs/mkdocs.yml
- docs/src/faq.md
> docs: add initial stub of FAQ section

- config/crd/bases/postgresql.cnpg.io_clusters.yaml
- config/crd/bases/postgresql.cnpg.io_poolers.yaml
> chore: Update generated files with Kubernetes 1.24 descriptions

- hack/e2e/run-e2e.sh
- tests/utils/release.go
- tests/utils/release_test.go
> tests: enable upgrade tests again

- Makefile
- README.md
- docs/src/cnpg-plugin.md
> doc: add an easy way to test the current development version

- Makefile
getwoke/woke 0.9.0 -> 0.18.1
github-action-spellcheck 0.14.0-> 0.23.0
> chore: update version of woke and spellcheck

- .github/workflows/codeql-analysis.yml
- internal/management/controller/cache.go
- internal/management/controller/instance_controller.go
> chore: avoid running CodeQL in non Go files

- contribute/development_environment/README.md
Adding the Airplay pre-requisites for MacOS users
> docs: Update README.md

- README.md
> doc: update README with relevant and related blog articles

- docs/src/backup_recovery.md
- docs/src/bootstrap.md
> docs: add section describing recovery clusters with a backup section

- .github/workflows/registry-clean.yml
> ci: do not run package cleanup on push

- docs/src/installation_upgrade.md
> doc: fix helm chart URL for the install process

- .github/workflows/release-publish.yml
- .goreleaser.yml
> feat: adding Krew support to GoReleaser

- .wordlist-en-custom.txt
- docs/src/faq.md
> doc: Add FAQ about time zone configuration

- tests/e2e/asserts_test.go
> tests: Improves E2E resiliency to transient network failures

- internal/cmd/plugin/report/deployments/deployments.go
- internal/cmd/plugin/report/operator_report.go
Closes: https://github.com/cloudnative-pg/cloudnative-pg/issues/122
Signed-off-by: Tao LI [tao.li@enterprisedb.com](mailto:tao.li@enterprisedb.com)
> fix: parse configmap name and secrets name from operator deployment

- .wordlist-en-custom.txt
- docs/src/faq.md
> doc: FAQ about database size limits in Kubernetes

- controllers/cluster_controller.go
- controllers/replicas.go
> fix: Support updates of inherited labels and annotations on PVCs

- .wordlist-en-custom.txt
- api/v1/cluster_types.go
- api/v1/cluster_webhook.go
- config/crd/bases/postgresql.cnpg.io_backups.yaml
- config/crd/bases/postgresql.cnpg.io_clusters.yaml
- docs/src/api_reference.md
- docs/src/backup_recovery.md
- docs/src/samples/cluster-backup-azure-inherit.yaml
- pkg/management/barman/capabilities/detect.go
- pkg/management/barman/capabilities/type.go
- pkg/management/barman/commandbuilder.go
- pkg/management/barman/credentials/env.go
Closes https://github.com/cloudnative-pg/cloudnative-pg/issues/131
Signed-off-by: Valerio Del Sarto [valerio.delsarto@enterprisedb.com](mailto:valerio.delsarto@enterprisedb.com)
> feat: adding support for Azure AD Workload Identity

- internal/management/controller/instance_controller.go
This may result in spurious logs when every DDL is logged.
Closes #179
> feat: avoid executing DDL to reconcile extensions when not needed

- pkg/management/postgres/instance.go
> fix: CSV logpipe initialization order inside WithActiveInstance function

- pkg/management/postgres/restore.go
> fix: serverName handling when restoring from a backup

- api/v1/cluster_types.go
- api/v1/zz_generated.deepcopy.go
- config/crd/bases/postgresql.cnpg.io_backups.yaml
- config/crd/bases/postgresql.cnpg.io_clusters.yaml
- docs/src/api_reference.md
- pkg/management/barman/credentials/env.go
> feat: adds AWS_DEFAULT_REGION to barman env

- internal/management/controller/instance_controller.go
> fix: avoid dropping extensions when not needed

- tests/e2e/configuration_update_test.go
Refactor the configuration update test case to make each 
upgrade scenario run in separate spec. 
Closes #126 
> test: refactor E2E configuration test case

- api/v1/cluster_webhook_test.go
- pkg/postgres/version.go
- pkg/postgres/version_test.go
> fix: webhook accepting image tags such as 15beta1

- config/manager/default-monitoring.yaml
- docs/src/samples/cnpg-basic-monitoring.yaml
- pkg/management/postgres/metrics/collector.go
> chore: downgrades skipped monitoring query messages to debug level

- tests/e2e/asserts_test.go
- tests/e2e/backup_restore_test.go
- tests/e2e/commons_test.go
- tests/e2e/replica_mode_cluster_test.go
- tests/e2e/wal_restore_parallel_test.go
- tests/utils/environment.go
- tests/utils/minio.go
fix the end to end test case failure 
Closes #266 
> test: fix backup restore e2e test failure

- api/v1/cluster_webhook.go
> chore: adds webhook validation for syncReplicaElectionConstraints

- controllers/replicas.go
- pkg/postgres/status.go
> feat: improve instances status logging during switchover and failover

- .wordlist-en-custom.txt
- docs/mkdocs.yml
- docs/src/architecture.md
- docs/src/replica_cluster.md
- docs/src/replication.md
> Clarify documentation on `syncReplicaElectionConstraint`

- controllers/cluster_delete_test.go
> test: ensure cache is indexed before testing dangling configmap

- internal/cmd/plugin/status/status.go
> feat(plugin): add nodename in the instance status section

- .github/workflows/continuous-delivery.yml
> ci: let's run less E2E

- docs/src/index.md
- docs/src/operator_capability_levels.md
- docs/src/release_notes.md
> doc: Release Notes for 1.16.0

- docs/src/supported_releases.md
> doc: integrate the supported releases page

- pkg/management/postgres/instance.go
- pkg/management/postgres/pidfile.go
- pkg/management/postgres/pidfile_test.go
> fix: e2e failure for online upgrade test cases

- docs/src/index.md
- docs/src/release_notes.md
- docs/src/supported_releases.md
> doc: Release Notes for 1.15.2

- tests/e2e/fixtures/metrics/.gitignore
- tests/e2e/fixtures/metrics/cluster-replica-tls-with-metrics.yaml.template
- tests/e2e/fixtures/metrics/custom-queries-for-replica-cluster.yaml
- tests/e2e/metrics_test.go
> test: E2E on replica cluster with basic monitoring queries 

- docs/src/installation_upgrade.md
> fix(docs): operator manifest URL for 1.15

- pkg/management/postgres/logicalimport/role.go
> chore: removes unnecessary rows.Err() call during role import

- api/v1/cluster_configuration_test.go
- api/v1/suite_test.go
> test: add coverage for synchronous replica election

- controllers/cluster_create_test.go
- controllers/cluster_delete_test.go
- controllers/cluster_scale_test.go
- controllers/cluster_status_test.go
- controllers/suite_test.go
> test(controllers): add support for custom k8sClient

- .github/workflows/continuous-delivery.yml
ok to merge action will not fail if precondition is not meet
Closes #308 
> ci: refine ok to merge step to avoid failure

- .wordlist-en-custom.txt
> doc: fix spellchecker errors

- docs/src/replica_cluster.md
> doc: fix link to sample in replica clusters page

- CONTRIBUTING.md
- docs/README.md
> doc: explain how to contribute documentation

- tests/utils/cluster.go
- tests/utils/environment.go
> test: add backup object context logs in DumpNamespaceObjects

- pkg/management/postgres/configuration.go
> fix: removing unsafe debug entry

- api/v1/cluster_types.go
- config/crd/bases/postgresql.cnpg.io_backups.yaml
- config/crd/bases/postgresql.cnpg.io_clusters.yaml
- docs/src/api_reference.md
Correct comments in `BarmanCredentials` struct and update manifests accordingly.
Closes: #515 
> chore: correct comments per fields in `BarmanCredentials`

- docs/src/ssl_connections.md
Signed-off-by: Dario Tranchitella <dario@tranchitella.eu>
> fix(docs): wrong path to ssl certificate

- Makefile
> chore: updated spellcheck version in Makefile

- controllers/replicas.go
> chore: log pvc label update once the operation is done

- docs/src/bootstrap.md
- docs/src/database_import.md
- pkg/management/external/external.go
- pkg/management/external/external_test.go
- pkg/management/external/suite_test.go
- pkg/management/postgres/initdb.go
This PR contains two fixes. For the description see the relative commits
Closes #392
Closes #571
> fix(externalcluster): sslmode is set based on the passed parameters

- .wordlist-en-custom.txt
- docs/mkdocs.yml
- docs/src/faq.md
- docs/src/index.md
- docs/src/operator_capability_levels.md
- docs/src/postgis.md
- docs/src/samples.md
- docs/src/samples/postgis-example.yaml
Introduce the concept of "PostGIS cluster" and explain how to create
it using the community images. Update also the rest of the documentation
to highlight PostGIS.
Closes #568
> doc: add section about PostGIS

- docs/src/postgresql_conf.md
> doc: fix value of `unix_socket_directories`

- hack/show-release-diffs.sh
> chore(linter): fix warnings in show-release-diffs.sh script

- docs/src/release_notes/v1.15.md
- docs/src/release_notes/v1.16.md
> doc: release notes for 1.16.1 and 1.15.3

- .github/postgres-versions-update.py
Instead of just relying on the GitHub API to do that, we are now using
the Docker API which are usually less prone to be cached.
Closes #589
> feat: use the Docker API while updating the PostgreSQL version list

- docs/src/release_notes/edb-cloud-native-postgresql.md
- docs/src/release_notes/v1.15.md
- docs/src/release_notes/v1.16.md
> doc: update release notes with the new date

- .github/workflows/release-publish.yml
> fix: fixing the tag variable for releases

- .github/workflows/release-publish.yml
This will fix the change done in issue #606 to work as expected
Closes #607
> fix: the env.TAG variable will not start with a v

- controllers/cluster_controller.go
- controllers/cluster_scale.go
- controllers/cluster_scale_test.go
- controllers/cluster_status.go
- controllers/cluster_status_test.go
- controllers/replicas.go
- controllers/replicas_test.go
- pkg/specs/jobs.go
- pkg/specs/pods.go
- pkg/specs/pvcs.go
- pkg/utils/labels_annotations.go
Closes #550
Descriptions of what is done are contained in each commit. Do not squash.
> chore: properly recognize `instances` pods

- .github/dependabot.yml
- .github/workflows/chatops-dispatcher.yml
- .github/workflows/chatops-receiver.yml
- .github/workflows/continuous-delivery.yml
- .github/workflows/latest-postgres-version-check.yml
- .github/workflows/registry-clean.yml
- .github/workflows/release-publish.yml
> chore: add comments to workflows for clarity

- tests/e2e/asserts_test.go
- tests/e2e/fixtures/base/cluster-storage-class.yaml.template
- tests/e2e/pg_wal_volume_test.go
- tests/e2e/pvc_deletion_test.go
- tests/e2e/rolling_update_test.go
- tests/e2e/scaling_test.go
- tests/e2e/switchover_test.go
- tests/utils/storage.go
Integrate E2E for role label propagation to PVCs.
E2E for #631.
> tests: E2E for label propagation to PVCs

- docs/src/connection_pooling.md
> doc: fix missing configurable options for PgBouncer

- internal/cmd/manager/instance/run/lifecycle/lifecycle.go
- pkg/management/postgres/instance.go
- pkg/management/postgres/probes.go
- pkg/management/postgres/webserver/remote.go
- pkg/management/upgrade/upgrade.go
> Atomically check whether inplace instance upgrade is in progress

- api/v1/cluster_webhook.go
- tests/e2e/asserts_test.go
- tests/e2e/fixtures/storage_expansion/cluster-storage-expansion.yaml.template
> tests: Expand PVC resizing E2E to cover the walStorage

- pkg/management/postgres/instance.go
> fix: avoid passing Instance by value

- tests/e2e/fixtures/upgrade/cluster-restore.yaml.template
- tests/e2e/fixtures/upgrade/cluster1.yaml.template
- tests/e2e/fixtures/upgrade/cluster2.yaml.template
> chore: reduce resource consumption for PostgreSQL in E2E tests

- docs/src/release_notes.md
> doc: v1.17 is missing in the index of release notes

- contribute/release_procedure.md
> doc: procedure for new release branch from main

- tests/e2e/upgrade_test.go
> test: relax E2E upgrade test timeouts

- api/v1/cluster_webhook.go
- internal/management/controller/instance_controller.go
- internal/management/controller/slots/reconciler/replicationslot.go
- internal/management/controller/slots/reconciler/replicationslot_test.go
- internal/management/controller/slots/runner/runner.go
> chore: adds the cleanup logic in case of disable

- .github/workflows/chatops-dispatcher.yml
- .github/workflows/chatops-receiver.yml
- .github/workflows/continuous-delivery.yml
> ci: Nightly build kubectl plugin in case it breaks release 

- docs/k8s-api-docgen.yaml
- docs/src/api_reference.md
- docs/src/before_you_start.md
- hack/e2e/rke-ec2/README.md
- hack/e2e/rke-ec2/interface.tf
- hack/e2e/rke-ec2/versions.tf
> doc: remove leftover references to K8S 1.19 and 1.20

- internal/cmd/plugin/report/logs.go
- pkg/utils/logs/logs.go
- tests/e2e/suite_test.go
- tests/utils/cluster.go
dump the operator log if it is restarted during e2e test
Closes: #705 
> test: dump operator log if it is restarted

- .github/workflows/continuous-delivery.yml
> ci: fix 'ok to merge' labeling

- .wordlist-en-custom.txt
- docs/src/monitoring.md
> doc: add instructions on how to inspect exported metrics

- .wordlist-en-custom.txt
- docs/src/faq.md
Closes #778
Signed-off-by: Jonathan Battiato <jonathan.battiato@enterprisedb.com>
> doc: FAQ about cluster impact during Operator outage

- docs/src/release_notes/v1.15.md
- docs/src/release_notes/v1.16.md
- docs/src/release_notes/v1.17.md
- docs/src/supported_releases.md
> doc: Release notes for 1.17.1

- docs/src/release_notes/v1.15.md
- docs/src/release_notes/v1.16.md
- docs/src/supported_releases.md
> doc: Release notes for 1.16.3

- docs/src/release_notes/v1.15.md
- docs/src/release_notes/v1.16.md
- docs/src/release_notes/v1.17.md
- docs/src/supported_releases.md
> doc: Release notes for 1.17.1, 1.16.3, and 1.15.5

- docs/src/release_notes/v1.15.md
- docs/src/release_notes/v1.16.md
- docs/src/release_notes/v1.17.md
- internal/cmd/manager/walarchive/cmd.go
- internal/management/controller/instance_controller.go
- pkg/management/barman/archiver/archiver.go
- pkg/management/postgres/initdb.go
- pkg/management/postgres/restore.go
- tests/e2e/fixtures/backup/backup_restore_safety/cluster-with-backup-minio.yaml.template
> chore: improve archive WAL check

- docs/src/installation_upgrade.md
- pkg/versions/versions.go
- releases/cnpg-1.17.1.yaml
Co-authored-by: Jaime Silvela <jaime.silvela@enterprisedb.com>
> Version tag to 1.17.1

- internal/cmd/manager/walarchive/cmd.go
- pkg/utils/labels_annotations.go
> feat: adds skipEmptyWalArchiveCheck annotation

- pkg/management/postgres/webserver/remote.go
> refactor: improve instance manager liveness probe readability

- docs/src/database_import.md
Signed-off-by: imusmanmalik <usmanmalik@engineer.com>
> docs: Fix typo in Example of monolith import type

- internal/cmd/plugin/status/cmd.go
- internal/cmd/plugin/status/status.go
- pkg/management/postgres/probes.go
- pkg/postgres/status.go
> feat: adds replication slot status to plugin `status`

- .wordlist-en-custom.txt
- docs/mkdocs.yml
- docs/src/controller.md
- docs/src/faq.md
> doc: add a section about our custom controller

- pkg/management/postgres/instance.go
- pkg/management/postgres/probes.go
> chore: decouples  from the instance struct

- docs/src/e2e.md
> doc: Group and Add E2E details under `End-to-End Tests` section.

- hack/e2e/run-e2e.sh
> fix: shellcheck is failing

- README.md
- docs/src/index.md
- docs/src/monitoring.md
- docs/src/supported_releases.md
> doc: update documentation for new release

- contribute/release_procedure.md
> docs: enhance release procedure

- hack/e2e/run-e2e.sh
> chore: enable upgrade test case for k8s v1.25

- .github/workflows/backport.yml
Add workflow to auto backport merged pr in main branch to release branches
closes: #964 
> ci: add backport pull request workflow

- Makefile
> test: set `KUBEBUILDER_CONTROLPLANE_STOP_TIMEOUT` and `KUBEBUILDER_CONTROLPLANE_START_TIMEOUT`

- .github/workflows/backport.yml
> ci: fix backport workflow failed to retrive the commit

- controllers/suite_test.go
> test: refine the envTest creation inside the controllers package (#1029)

- GOVERNANCE.md
> doc: document emeritus status for maintainers in GOVERNANCE.md

- controllers/cluster_restore.go
> fix: limit the orphan pvc list inner the cluster namespace

- hack/e2e/run-e2e.sh
closes #1043 
Signed-off-by: Danish Khan <danish.khan@enterprisedb.com>
> ci: Getting Visibility Into Long-Running Specs

- tests/utils/release.go
> tests: fix tag detection

- .github/workflows/backport.yml
- contribute/release_procedure.md
> ci: backport should not create issue if release branch not select

- docs/src/logging.md
- pkg/management/log/flags.go
- pkg/specs/containers.go
> feat: allow fields remapping in JSON logs

- docs/src/monitoring.md
- docs/src/operator_capability_levels.md
> doc: remove references to CNPG sandbox

- .github/workflows/continuous-delivery.yml
- .github/workflows/continuous-integration.yml
Give default value for schedule workflow
Closes: #1133 
> fix: Give default value for schedule workflow

- pkg/resources/doc.go
- pkg/resources/patchtype.go
- pkg/resources/request.go
> chore: add a fluent request client to ease API calls

- controllers/cluster_create.go
> fix: ensure that we create secret and services only when not found

- .github/workflows/continuous-delivery.yml
- .github/workflows/continuous-integration.yml
- .github/workflows/release-publish.yml
- go.mod
> feat: update Go version from 1.18 to 1.19

- controllers/cluster_scale.go
- controllers/cluster_scale_test.go
- controllers/suite_test.go
- tests/e2e/asserts_test.go
- tests/e2e/scaling_test.go
closes #1128 
Signed-off-by: Danish Khan <danish.khan@enterprisedb.com>
> fix:  wal pvc not deleted while scaling down.

- contribute/README.md
- docs/src/supported_releases.md
> doc: link to the "Release updates" discussion

- .github/workflows/continuous-delivery.yml
- tests/e2e/asserts_test.go
- tests/e2e/backup_restore_test.go
- tests/e2e/cluster_microservice_test.go
- tests/e2e/cluster_monolithic_test.go
- tests/e2e/cluster_setup_test.go
- tests/e2e/configuration_update_test.go
- tests/e2e/connection_test.go
- tests/e2e/drain_node_test.go
- tests/e2e/failover_test.go
- tests/e2e/fastswitchover_test.go
- tests/e2e/hibernation_test.go
- tests/e2e/metrics_test.go
- tests/e2e/operator_unavailable_test.go
- tests/e2e/pg_basebackup_test.go
- tests/e2e/pg_data_corruption_test.go
- tests/e2e/pgbouncer_test.go
- tests/e2e/replica_mode_cluster_test.go
- tests/e2e/suite_test.go
- tests/e2e/syncreplicas_test.go
- tests/utils/environment.go
- tests/utils/postgres.go
- tests/utils/psql_client.go
- tests/utils/secrets.go
- tests/utils/service.go
- tests/utils/time.go
> test: refactor e2e to use psql client pod.

- pkg/postgres/status.go
> fix: IsPostgresqlReady condition inverted

- contribute/release_procedure.md
- docs/src/release_notes/v1.16.md
- docs/src/release_notes/v1.17.md
- docs/src/release_notes/v1.18.md
- docs/src/supported_releases.md
> doc: release notes for December release

- docs/src/release_notes/v1.18.md
Add features left out of the release notes
> Amend 1.18.1 release notes

- tests/e2e/upgrade_test.go
NOTE: should be applied on 1.17 ONLY.
> test: fix online upgrade test in 1.17

- tests/e2e/suite_test.go
- tests/utils/commons.go
- tests/utils/psql_client.go
- tests/utils/run.go
> test: avoid starting postgres server in the psql pod

- tests/utils/secrets.go
> Improve testUtils.GetCredentials to support custom secrets

- hack/e2e/run-e2e.sh
- tests/e2e/suite_test.go
> test: enhance E2E test's observability

- internal/pgbouncer/management/controller/manager.go
- pkg/certs/k8s.go
- pkg/fileutils/fileutils.go
- pkg/fileutils/fileutils_test.go
- pkg/fileutils/suite_test.go
- pkg/management/barman/spool/spool.go
- pkg/management/postgres/backup.go
- pkg/management/postgres/initdb.go
- pkg/management/postgres/instance.go
- pkg/management/postgres/logicalimport/constants.go
- pkg/management/postgres/logpipe/linelogpipe.go
- pkg/management/postgres/logpipe/logpipe.go
- pkg/management/postgres/restore.go
- pkg/management/postgres/restore_test.go
> chore: fixing MoveDirectoryContent to work with subdirectories

- pkg/reconciler/persistentvolumeclaim/resources_test.go
- pkg/reconciler/persistentvolumeclaim/status.go
- pkg/reconciler/persistentvolumeclaim/suite_test.go
> refactor: improve readability of persistentvolumeclaim.EnrichStatus

- api/v1/cluster_types.go
- api/v1/cluster_webhook.go
- controllers/cluster_controller.go
- controllers/cluster_upgrade.go
- docs/src/storage.md
- internal/cmd/manager/instance/run/cmd.go
- internal/management/controller/instance_startup.go
- pkg/reconciler/persistentvolumeclaim/status.go
- pkg/specs/jobs.go
- pkg/specs/volumes.go
- tests/e2e/pg_wal_volume_test.go
> feat: allowing walStorage to be changed on existing cluster

- .github/workflows/continuous-delivery.yml
- .github/workflows/continuous-integration.yml
> ci: restore a proper workflow-dispatch action tag

- docs/src/before_you_start.md
- docs/src/storage.md
> doc: define a PVC group

- internal/cmd/manager/instance/run/lifecycle/run.go
Closes: #665
Signed-off-by: Tamara Nocentini <tamara.nocentini@enterprisedb.com>
> feat: comment streaming_replica user

- .github/workflows/continuous-delivery.yml
- .github/workflows/continuous-integration.yml
- .github/workflows/release-publish.yml
> ci: implement workaround for push failures on ghcr

- docs/src/supported_releases.md
> doc: specify Postgres versions supported by each minor release

- .wordlist-en-custom.txt
- docs/src/cnpg-plugin.md
explain how to download deb or rpm packages and install locally
Closes #1356 
> doc: add instructions on installing plugin using packages

- README.md
> chore: updating Philippe Scorsolini's company

- pkg/reconciler/persistentvolumeclaim/reconciler.go
> fix: ensure that the pvc roles are always consistent

- docs/src/installation_upgrade.md
> docs: document webhooks' issues on GKE

- docs/src/release_notes/old/v1.15.md
- pkg/management/pgbouncer/metricsserver/pools.go
- pkg/specs/pgbouncer/deployments.go
- tests/e2e/pgbouncer_metrics_test.go
> chore: Bump pgbouncer from 1.17.0 to 1.18.0

- controllers/cluster_upgrade.go
- controllers/cluster_upgrade_test.go
- pkg/specs/jobs.go
- pkg/specs/pods.go
- pkg/specs/pods_test.go
- pkg/utils/labels_annotations.go
> fix: ensure that we update environment variables only when needed

- .github/workflows/continuous-delivery.yml
> test(e2e): change github action which clean the runner disk space

- api/v1/cluster_webhook_test.go
Validation was already correctly introduced by #914, but we did not add a test case for it.
Fixes #884
> test: verify storage configured correctly

- .github/workflows/continuous-delivery.yml
- .github/workflows/continuous-integration.yml
- .github/workflows/release-publish.yml
> ci: drop workaround for buildx

- pkg/management/postgres/backup.go
- pkg/management/postgres/wal.go
- pkg/management/postgres/wal_test.go
> fix: do not run CHECKPOINT as streaming_replica user

- README.md
> doc: add Star History Chart

- pkg/reconciler/persistentvolumeclaim/build_test.go
- pkg/reconciler/persistentvolumeclaim/reconciler.go
- pkg/reconciler/persistentvolumeclaim/reconciler_test.go
- pkg/reconciler/persistentvolumeclaim/resources_test.go
- pkg/reconciler/persistentvolumeclaim/suite_test.go
> fix: update role labels of unattached PVCs

- .github/workflows/continuous-integration.yml
- tests/utils/environment.go
> ci: golangci-lint github action reports error

- docs/src/release_notes.md
- docs/src/release_notes/v1.17.md
- docs/src/release_notes/v1.18.md
- docs/src/release_notes/v1.19.md
- docs/src/supported_releases.md
> doc: release notes Feb 2023

- .github/workflows/continuous-delivery.yml
Closes: #1453 
Signed-off-by: Tao Li [tao.li@enterprisedb.com](mailto:tao.li@enterprisedb.com)
> ci: optimize the cleanup disk github action

- pkg/management/log/flags.go
- pkg/management/log/log.go
> chore: add support for http json logs

- controllers/cluster_pki.go
> fix: error message when generating streaming replication certificate

- .github/workflows/backport.yml
> ci: always add backport labels for new created pr

- docs/src/connection_pooling.md
> doc: fix resource customization example in the pooler page

- controllers/scheduledbackup_controller.go
> chore: use patch instead of update inside scheduledbackup_controller

- docs/src/samples/cluster-example-with-roles.yaml
- internal/cmd/manager/instance/run/cmd.go
- internal/management/controller/instance_controller.go
- internal/management/controller/roles/contract.go
- internal/management/controller/roles/doc.go
- internal/management/controller/roles/postgres.go
- internal/management/controller/roles/runnable.go
- pkg/management/postgres/instance.go
> Create runner to manage roles on the database

- .github/workflows/continuous-delivery.yml
- docs/src/installation_upgrade.md
> ci: fix the upload process of development operator manifests

- pkg/management/postgres/backup.go
> fix: commit successful backup during the backup maintance step

- README.md
> docs: fix ADOPTERS.md link in README

- pkg/management/postgres/probes.go
- pkg/management/postgres/probes_test.go
> fix: error handling in the probes

- Makefile
- controllers/cluster_delete_test.go
- controllers/cluster_status_test.go
- controllers/suite_test.go
> chore: remove manager dependency from controller unit tests

- .github/renovate.json5
- .github/workflows/backport.yml
- .github/workflows/continuous-delivery.yml
- .github/workflows/continuous-integration.yml
> chore: stop backporting or running tests on branch release-1.17

- controllers/cluster_controller_test.go
- controllers/cluster_status_test.go
- controllers/suite_test.go
> test: ensure that the scale-down behaviour remain consistent

- docs/src/supported_releases.md
> docs: remove postgres 10 support from document

- tests/e2e/fastfailover_test.go
- tests/e2e/fastswitchover_test.go
- tests/e2e/fixtures/upgrade/cluster-restore.yaml.template
- tests/e2e/fixtures/upgrade/cluster1.yaml.template
- tests/e2e/fixtures/upgrade/cluster2.yaml.template
- tests/e2e/scaling_test.go
- tests/e2e/switchover_test.go
- tests/e2e/update_user_test.go
> test: always run E2Es in unique namespaces

- internal/management/controller/instance_controller.go
- pkg/management/postgres/configuration.go
- pkg/management/postgres/initdb.go
- pkg/management/postgres/restore.go
> fix: apply the full configuration during the init job

- docs/src/monitoring.md
For folks to help understand where this metric comes from.
Closes: #1980
> doc: note backup requirement on metric

- docs/src/cnpg-plugin.md
> doc: cover `cnpg` plugin upgrade with `krew`

- docs/src/rolling_update.md
> doc: update document with more information about in-place restart

- internal/cmd/manager/controller/cmd.go
> fix: run controller cmd with `SilenceErrors`

- tests/e2e/apparmor_test.go
- tests/e2e/backup_restore_test.go
- tests/e2e/cluster_microservice_test.go
- tests/e2e/pgbouncer_test.go
- tests/e2e/pgbouncer_types_test.go
- tests/utils/environment.go
- tests/utils/namespace.go
- tests/utils/namespace_test.go
> test: deprecate CreateNamespace

- hack/e2e/run-e2e-k3d.sh
- hack/e2e/run-e2e-kind.sh
- hack/setup-cluster.sh
Also fix the order of arguments in setup-cluster.sh call to support bsd getopt.
Closes: #2020
> test: fix k3s images detection method

- tests/utils/minio.go
> test: make sure minio-client config directory is writable

- internal/cmd/manager/controller/controller.go
> chore: avoid multiple casting of webhook.DefaultServer

- tests/e2e/asserts_test.go
- tests/e2e/backup_restore_test.go
- tests/e2e/failover_test.go
- tests/e2e/logs_test.go
- tests/e2e/operator_ha_test.go
- tests/e2e/operator_unavailable_test.go
- tests/e2e/pg_data_corruption_test.go
- tests/e2e/pvc_deletion_test.go
- tests/e2e/suite_test.go
> test: use gracePeriodSeconds=1 in e2e test while deleting pod

- config/crd/bases/postgresql.cnpg.io_backups.yaml
- config/crd/bases/postgresql.cnpg.io_clusters.yaml
- config/crd/bases/postgresql.cnpg.io_poolers.yaml
- config/crd/bases/postgresql.cnpg.io_scheduledbackups.yaml
- config/rbac/role.yaml
- config/webhook/manifests.yaml
> chore: update manifests

- pkg/management/postgres/webserver/metricserver/pg_collector.go
> fix: report the correct PG version in the metrics

- internal/management/controller/roles/runnable.go
- internal/management/controller/roles/runnable_test.go
> chore: improve signature and add unit test for getPassword

- docs/src/benchmarking.md
- docs/src/cnpg-plugin.md
- internal/cmd/plugin/pgbench/cmd.go
- internal/cmd/plugin/pgbench/pgbench.go
> chore: add `nodeSelector` to `cnpg pgbench` jobs

- docs/src/installation_upgrade.md
> doc: fix instructions to install latest snapshot

- controllers/cluster_controller.go
> chore: avoid executing multiple times `SetupLogger`

- .wordlist-en-custom.txt
- docs/src/storage.md
> doc: explain static pre-provisioning of volumes

- .wordlist-en-custom.txt
- docs/mkdocs.yml
- docs/src/networking.md
- docs/src/samples/networkpolicy-example.yaml
- docs/src/security.md
- docs/src/troubleshooting.md
adds documentation on networking and potential trouble
and fixes
Closes #2230
> doc: add content on networking

- .github/workflows/snyk.yml
Since the project CloudNativePG was accepted as project by the Snyk project, we can now integrate properly with the code scanning.
Closes #48
> chore: add Snyk scanning

- controllers/cluster_controller.go
> fix: always reconcile metadata

- internal/management/controller/instance_controller.go
- pkg/management/postgres/configuration.go
- pkg/management/postgres/instance.go
- pkg/management/postgres/instance_replica.go
> chore: encapsulate configurationReload and refreshReplicaConfiguration logic

- tests/e2e/backup_restore_test.go
- tests/e2e/eviction_test.go
- tests/e2e/fastfailover_test.go
- tests/e2e/fastswitchover_test.go
- tests/e2e/replica_mode_cluster_test.go
- tests/e2e/wal_restore_parallel_test.go
- tests/utils/cloud_vendor.go
- tests/utils/environment.go
> chore: remove the deprecated cloud detected code

- docs/src/faq.md
> doc: add a few more entries in FAQs

- docs/src/postgresql_conf.md
> doc: minor fix in `pg_failover_slots` documentation

- hack/setup-cluster.sh
This reverts commit 447a2ab7aa95de5ee75d800db6b1f862707fb4f5.
> revert: "tests: compatibility with latest Docker Desktop (#2394)"

- docs/src/samples/monitoring/grafana-configmap.yaml
- docs/src/samples/monitoring/grafana-dashboard.json
Fixes #2411
Signed-off-by: Daniel Chambre <smiyc@pm.me>
> changed the $cluster-.* regex

- config/crd/bases/postgresql.cnpg.io_backups.yaml
- config/crd/bases/postgresql.cnpg.io_clusters.yaml
- config/crd/bases/postgresql.cnpg.io_poolers.yaml
- config/crd/bases/postgresql.cnpg.io_scheduledbackups.yaml
the outdated CRD is blocking the continuous integration's CRD check
> fix: update CRD with controller-gen

- pkg/management/postgres/logicalimport/database.go
- pkg/management/postgres/logicalimport/database_test.go
- pkg/management/postgres/logicalimport/microservice.go
- pkg/management/postgres/logicalimport/monolith.go
- pkg/management/postgres/logicalimport/role.go
- pkg/management/postgres/logicalimport/role_test.go
- pkg/management/postgres/logicalimport/roleinheritance.go
- pkg/management/postgres/logicalimport/roleinheritance_test.go
- pkg/management/postgres/logicalimport/suite_test.go
> chore: add Pooler interface and test coverage to logicalimports

- api/v1/pooler_types.go
- pkg/specs/pgbouncer/deployments_test.go
- pkg/specs/pgbouncer/podmonitor_test.go
- pkg/specs/pgbouncer/rbac_test.go
- pkg/specs/pgbouncer/services_test.go
- pkg/specs/pgbouncer/suite_test.go
> test: add unit test coverage to specs/pgbouncer

- pkg/management/postgres/metrics/mapping_test.go
> test: add metrics/mapping unit tests

- pkg/fileutils/compatibility/windows.go
Fix the windows os compile issue
> fix: fix windows compile issue

- api/v1/cluster_types.go
- config/crd/bases/postgresql.cnpg.io_clusters.yaml
- docs/src/api_reference.md
- docs/src/bootstrap.md
> fix: by default recovery should be exclusive

- internal/management/controller/slots/infrastructure/postgresmanager_test.go
- internal/management/controller/slots/infrastructure/suite_test.go
- internal/management/controller/slots/reconciler/replicationslot_test.go
> test: improve unit test coverage for slots pkg

- pkg/management/pgbouncer/metricsserver/pools.go
> chore: reorganize collectShowPools variables

- .github/workflows/continuous-delivery.yml
- contribute/e2e_testing_environment/README.md
- internal/cmd/plugin/snapshot/cmd.go
- tests/e2e/volume_snapshot_test.go
- tests/labels.go
- tests/utils/backup.go
> feat: add `volume-snapshot-suffix` optional argument to snapshot command

- .wordlist-en-custom.txt
- docs/src/release_notes/v1.19.md
- docs/src/release_notes/v1.20.md
- docs/src/supported_releases.md
> doc: release notes 1.20.2, 1.19.4

- tests/e2e/asserts_test.go
- tests/e2e/fixtures/pvc_snapshot/cluster-pvc-snapshot-restore.yaml.template
- tests/e2e/fixtures/pvc_snapshot/cluster-pvc-snapshot.yaml.template
- tests/e2e/pvc_snapshot_test.go
- tests/utils/cluster.go
- tests/utils/environment.go
> test: add E2E test for the snapshot feature

- api/v1/cluster_types_test.go
- api/v1/cluster_webhook_test.go
- internal/cmd/plugin/fio/fio.go
- internal/management/controller/slots/reconciler/replicationslot_test.go
- internal/management/controller/slots/runner/runner_test.go
- pkg/management/postgres/logicalimport/roleinheritance_test.go
- pkg/reconciler/persistentvolumeclaim/reconciler_test.go
- tests/utils/azurite.go
- tests/utils/curl.go
- tests/utils/minio.go
- tests/utils/psql_client.go
- tests/utils/replication_slots.go
- tests/utils/webapp.go
> fix: fix linter failed in ci workflow

- .github/workflows/continuous-integration.yml
> ci: enforce linter in ci always run as it is a required check

- pkg/reconciler/instance/metadata.go
- pkg/reconciler/instance/metadata_test.go
- pkg/reconciler/persistentvolumeclaim/metadata.go
- pkg/specs/jobs.go
- pkg/specs/pods.go
- pkg/utils/labels_annotations.go
- pkg/utils/labels_annotations_test.go
> fix: add AppArmor only when the matching container is present

- docs/src/release_notes/old/v1.15.md
- docs/src/release_notes/old/v1.16.md
- docs/src/release_notes/old/v1.17.md
- docs/src/release_notes/old/v1.18.md
> Adjust admonition calling out EOL versions in release notes

- controllers/cluster_create.go
- pkg/specs/pg_pods.go
> fix: ensure that the primary instance is always recreated first

- docs/src/monitoring.md
- pkg/management/postgres/probes.go
- pkg/management/postgres/webserver/metricserver/wal.go
> fix(prometheus): set wal_write_time and wal_sync_time as float64

- config/certmanager/certificate.yaml
- config/crd/kustomization.yaml
- config/crd/patches/webhook_in_poolers.yaml
- config/default/kustomization.yaml
- config/default/mutatingwebhookcainjection_patch.yaml
- config/default/validatingwebhookcainjection_patch.yaml
> chore: update cert-manager CA injection scaffolding

- controllers/backup_controller.go
- controllers/backup_controller_test.go
- controllers/suite_test.go
- tests/e2e/backup_restore_test.go
> fix: execute reconciliation of backups unless they're marked as `failed` or `completed`

- controllers/backup_controller.go
- pkg/utils/labels_annotations.go
- tests/e2e/volume_snapshot_test.go
> feat: add the backupName label to the VolumeSnapshots

- internal/cmd/manager/walarchive/cmd.go
> fix: ensure that `ContinuousArchiving` is set as failed in case of errors

- pkg/reconciler/persistentvolumeclaim/resources.go
- tests/e2e/tablespaces_test.go
- tests/utils/timeouts.go
> feat: add tablespaces to existing cluster

- controllers/cluster_restore.go
- internal/cmd/plugin/hibernate/off.go
- internal/cmd/plugin/hibernate/on.go
- tests/e2e/hibernation_test.go
> chore: add `ClusterManifestAnnotationName` and `PgControldataAnnotationName`to hibernate cmd

- docs/src/benchmarking.md
> Removed nbsp from code block header

- internal/cmd/plugin/snapshot/cmd.go
- tests/e2e/volume_snapshot_test.go
- tests/utils/backup.go
> feat: add `label-backup-name` flag to snapshot command

- docs/src/connection_pooling.md
> fix(docs): how to inspect PgBouncer metrics

- pkg/specs/pods.go
- pkg/utils/labels_annotations.go
> chore: remove `postgresql` label name

- internal/management/controller/slots/runner/runner.go
> fix: Skip replication slot reconciliation if fenced

- controllers/cluster_controller.go
> chore: skip `architecture` checks on fenced instances

- docs/src/cloudnative-pg.v1.md
Fixes the currently broken main branch
> chore: align apidoc 

- .wordlist-en-custom.txt
- api/v1/cluster_types.go
- config/crd/bases/postgresql.cnpg.io_clusters.yaml
- docs/src/cloudnative-pg.v1.md
- docs/src/fencing.md
- docs/src/instance_manager.md
- internal/cmd/manager/instance/run/lifecycle/lifecycle.go
- internal/management/controller/instance_controller.go
- pkg/management/postgres/instance.go
- pkg/management/postgres/instance_test.go
- tests/e2e/asserts_test.go
- tests/e2e/fastfailover_test.go
- tests/e2e/fastswitchover_test.go
- tests/e2e/fixtures/fastfailover/cluster-fast-failover-with-repl-slots.yaml.template
- tests/e2e/fixtures/fastfailover/cluster-fast-failover.yaml.template
- tests/e2e/fixtures/fastfailover/cluster-syncreplicas-fast-failover.yaml.template
- tests/e2e/pg_wal_volume_test.go
- tests/e2e/switchover_test.go
- tests/utils/nodes/drain.go
> feat: Introduce 'smartStopDelay' for managing PG smart shutdown timeout

- api/v1/cluster_webhook.go
- api/v1/cluster_webhook_test.go
- tests/e2e/asserts_test.go
> chore: add webhook validation for `shared_buffers`

- api/v1/cluster_webhook_test.go
> fix: fix unit test failed

- tests/e2e/asserts_test.go
- tests/e2e/pg_wal_volume_test.go
> tests: allow to expect reaching one or multiple Cluster phases

- pkg/reconciler/backup/volumesnapshot/reconciler.go
- pkg/reconciler/backup/volumesnapshot/reconciler_test.go
- pkg/reconciler/backup/volumesnapshot/suite_test.go
> feat: avoid fencing instance unnecessarily in volume snapshots

- pkg/reconciler/backup/volumesnapshot/reconciler_test.go
> test: fix volumesnapshot unit test

- api/v1/cluster_types.go
- config/crd/bases/postgresql.cnpg.io_clusters.yaml
- docs/src/backup_volumesnapshot.md
- docs/src/cloudnative-pg.v1.md
> docs: explain `snapshotOwnerReference` field

- controllers/cluster_controller.go
> fix: ensure condition is false until the restart is complete

- controllers/scheduledbackup_controller.go
- internal/cmd/plugin/backup/cmd.go
- pkg/management/postgres/backup.go
- pkg/utils/time.go
- pkg/utils/time_test.go
> feat: standardize backup suffix between plugin backup and scheduledbackup

- controllers/cluster_create.go
- controllers/cluster_create_test.go
Starting from this patch, CloudNativePG reconciles the Services every
time the selectors change or when the labels or the annotations needs
to be changed.
From now on, we can fix the services created by old versions to the new
`cnpg.io/cluster` label available on Pods.
Closes #2917
> feat: reconcile cluster services

- api/v1/cluster_types_test.go
- api/v1/cluster_webhook.go
- api/v1/cluster_webhook_test.go
- docs/src/recovery.md
> fix: defaults to `app` owner and database during recovery

- docs/src/storage.md
> docs: remove any reference to cnp-bench

- docs/src/labels_annotations.md
- pkg/reconciler/backup/volumesnapshot/reconciler.go
- pkg/utils/labels_annotations.go
Add the date of the backup in ISO  8601 format (`YYYYMMDD`)
Closes #2983
> chore: add `cnpg.io/backupDate` to volume snapshots

- internal/cmd/plugin/backup/cmd.go
> fix: added name check to backup command

- internal/cmd/plugin/status/status.go
> feat: add primary timestamp and uptime to cnpg status

- api/v1/backup_types.go
- config/crd/bases/postgresql.cnpg.io_backups.yaml
> feat: add backup method in the printed columns

- .wordlist-en-custom.txt
- docs/src/storage.md
Provide a recommendation on block storage solutions to set replicas to 1 in order to avoid write amplification.
> docs: document write amplification issue

- tests/e2e/rolling_update_test.go
Relax the rolling update E2E test to dynamically accept any of the replicas following a switchover, instead of requiring that the second instance is always promoted.
Closes #3041
> test: accept any replica as new primary in rolling update E2Es

- pkg/multicache/multinamespaced_cache.go
> fix: check for nil map in multi namespaced cache

- docs/src/fencing.md
- pkg/management/postgres/instance.go
> feat: use fast shutdown for fencing

- README.md
- docs/src/architecture.md
> docs: add link to recommended architectures article

- .wordlist-en-custom.txt
- docs/src/release_notes.md
- docs/src/release_notes/v1.19.md
- docs/src/release_notes/v1.20.md
- docs/src/release_notes/v1.21.md
- docs/src/supported_releases.md
> docs: release notes for 1.21.0, 1.20.3 and 1.19.5

- docs/src/release_notes/v1.21.md
fixes wrong link in v1.21.0 Release Note #3089
Signed-off-by: Daniel Chambre [smiyc@pm.me](mailto:smiyc@pm.me)
> fix installation_upgrade.md link

- .github/renovate.json5
- .github/workflows/backport.yml
- .github/workflows/continuous-delivery.yml
- .github/workflows/continuous-integration.yml
> ci: add release-1.21 support in workflow

- .github/workflows/release-publish.yml
- Makefile
> ci: fixing the release of olm

- pkg/management/postgres/instance.go
> chore: encapsulate `InstanceCommand` implementations

- .github/workflows/release-publish.yml
> fix: krew publish process using new location created by GoReleaser

- .github/ISSUE_TEMPLATE/bug-report.yaml
> chore: add bug report issue template

- .github/workflows/codeql-analysis.yml
> chore: install common golang version in the CodeQL workflow

- internal/cmd/plugin/status/doc.go
- internal/cmd/plugin/status/status.go
- internal/cmd/plugin/status/status_test.go
- internal/cmd/plugin/status/suite_test.go
> fix: check if currentPrimaryTimestamp is empty

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/documentation.yml
- .github/ISSUE_TEMPLATE/feature.yml
> chore: add documentation issue template

- controllers/cluster_pki.go
Fixes #2542.
We forgot to properly handle the replication secret passed by the user as we are already doing for all other TLS secrets.
The [example](https://cloudnative-pg.io/documentation/1.21/certificates/#cert-manager-example_1) in the docs now actually works 🎉
> fix: accept provided replication client secret

- docs/src/faq.md
> docs: fix major Postgres version in FAQ

- api/v1/backup_types.go
- api/v1/backup_types_test.go
- api/v1/cluster_webhook_test.go
- api/v1/common_types.go
- controllers/cluster_create.go
- docs/src/recovery.md
- pkg/reconciler/persistentvolumeclaim/storagesource.go
- pkg/reconciler/persistentvolumeclaim/storagesource_test.go
> feat: support recovering from a volume snapshot backup object

- .vscode/settings.json
- .wordlist-en-custom.txt
- docs/src/commercial_support.md
- docs/src/connection_pooling.md
Signed-off-by: Betsy Gitelman <betsy.gitelman@enterprisedb.com>
> docs: review commercial support and connection pooling

- docs/src/release_notes.md
- docs/src/release_notes/old/v1.19.md
- docs/src/release_notes/v1.20.md
- docs/src/release_notes/v1.21.md
- docs/src/supported_releases.md
> docs: release notes for 1.21.1, 1.20.4, and 1.19.6 (EOL)

- .github/renovate.json5
- .github/workflows/backport.yml
- .github/workflows/continuous-delivery.yml
- .github/workflows/continuous-integration.yml
> chore: deprecate release branch 1.19

- .github/workflows/continuous-integration.yml
> ci: require read and security-events permissions for upload-sarif

- .github/workflows/continuous-integration.yml
- .github/workflows/release-publish.yml
- Dockerfile-ubi
Now we also build a UBI image to be used when building the OLM bundle
Closes: #3304
> feat: add UBI image for OLM bundle

- internal/cmd/plugin/report/cluster_report.go
Adds the cluster's PVC manifests to the cluster report produced
by the kubectl plugin's report sub-command.
Closes #3348
> feat: add PVC yamls to cluster report from plugin

- controllers/pooler_update.go
- controllers/pooler_update_test.go
This patch ensures that, in case we own the `Pooler` `ìmagePullSecret`, we keep it with the contents contained in the operator imagePullSecret.
> fix: reconcile `Pooler` `imagePullSecret`

- docs/src/labels_annotations.md
- docs/src/logging.md
Signed-off-by: Betsy Gitelman <betsy.gitelman@enterprisedb.com>
> Edits to labels and annotations and logging content

- controllers/pooler_update.go
This patch ensures that we reconcile the `RoleBinding` in case of differences.
Previously, only the RoleBinding creation was executed.
> fix: reconcile `Pooler` `RoleBinding`

- docs/src/labels_annotations.md
- pkg/specs/pgbouncer/deployments.go
- pkg/specs/pgbouncer/deployments_test.go
- pkg/utils/labels_annotations.go
> fix: add `podRole` label to Pooler deployment

- tests/e2e/fixtures/tablespaces/cluster-volume-snapshot-backup.yaml.template
- tests/e2e/fixtures/tablespaces/cluster-volume-snapshot-tablespaces.yaml.template
- tests/e2e/fixtures/tablespaces/cluster-with-tablespaces.yaml.template
- tests/e2e/tablespaces_test.go
- tests/utils/backup.go
> test: e2e test for volume snapshot backup with tablespaces

- internal/cmd/plugin/backup/cmd.go
> fix: evaluate 'immediate-checkpoint' and 'wait-for-archive' for  backup command

- .github/e2e-matrix-generator.py
- .github/e2e_test_timeout.json
- .github/generate-test-artifacts.py
- .github/workflows/backport.yml
- .github/workflows/chatops.yml
- .github/workflows/continuous-delivery.yml
- .github/workflows/continuous-integration.yml
- .github/workflows/registry-clean.yml
- .github/workflows/require-labels.yml
- hack/e2e/run-e2e.sh
This patch abstracts the input properties of several GHA workflows, improving their reusability and simplifying the way of overriding default values.
> ci: expose workflow's input properties

- docs/src/troubleshooting.md
Update the Troubleshooting guide with recent developments in the operator
tooling.
> docs: improve troubleshooting document

- docs/src/operator_capability_levels.md
Please see one query. Most edits were because of long sentences.
> docs: edits to operator capability levels topic

- docs/src/kubectl-plugin.md
- docs/src/samples/k9s/plugin.yml
> docs: add k9s plugin (#3566)

- .github/workflows/continuous-integration.yml
- Makefile
> ci: use latest go in  'olm-bundle' job of ci workflow

- internal/cmd/manager/instance/run/cmd.go
This reverts commit cdd52c735590ae2efcb8e422b13972c89f41e313.
> revert: "fix: adding shutdown delay to controller manager (#3354)"

- internal/cmd/plugin/backup/cmd.go
> fix(plugin): add cluster label to backups

- .wordlist-en-custom.txt
- api/v1/cluster_types.go
- api/v1/cluster_types_test.go
- api/v1/zz_generated.deepcopy.go
- config/crd/bases/postgresql.cnpg.io_clusters.yaml
- controllers/cluster_status.go
- docs/src/cloudnative-pg.v1.md
- internal/management/controller/externalservers/manager.go
- pkg/management/external/internal/pgpass/pgpass_test.go
> feat: watch secrets used by external clusters

- .wordlist-en-custom.txt
- docs/src/index.md
- docs/src/installation_upgrade.md
- docs/src/operator_capability_levels.md
- docs/src/release_notes.md
- docs/src/release_notes/v1.20.md
- docs/src/release_notes/v1.21.md
- docs/src/release_notes/v1.22.md
- docs/src/supported_releases.md
- docs/src/tablespaces.md
> docs: Release notes for 1.22.0, 1.21.2, and 1.20.5

- controllers/cluster_controller.go
> fix: Check the method ReconcilePods's Result

- tests/e2e/tablespaces_test.go
Since the user may be changed by a SecurityContext, we detect if there's a user set and we compare against it, otherwise, we use the default UID for the `postgres` user to compare with.
> fix: tests tablespaces file from the RunAsUser spec from container

- docs/src/kubectl-plugin.md
- docs/src/samples/k9s/plugins.yml
fixes #3675
Signed-off-by: Daniel Chambre [smiyc@pm.me](mailto:smiyc@pm.me)
> k9s plugins.yaml update

- controllers/cluster_upgrade_test.go
- pkg/specs/pods_test.go
- pkg/specs/podspec_diff.go
> fix: use semantic compare in pod spec drift detection 

- docs/src/installation_upgrade.md
- docs/src/kubectl-plugin.md
Fix typo in kubectl-plugin cnpg.
> docs: fix spelling of --watch-namespace plugin option

- docs/src/quickstart.md
> docs: fix example in quickstart

- docs/src/release_notes/v1.20.md
- docs/src/release_notes/v1.21.md
- docs/src/release_notes/v1.22.md
- docs/src/supported_releases.md
> docs: Release notes for 1.22.1, 1.21.3, and 1.20.6 (EOL)

- .github/e2e-matrix-generator.py
Added some missing exception to better explain when the e2e-matrix-generator.py 
fails running from different location or can't open files.
Closes #3784
> fix: add some missing exceptions

- hack/setup-cluster.sh
> fix: use the ROOT_DIR to execute make and get the version

- .github/workflows/continuous-delivery.yml
- tests/e2e/upgrade_test.go
> test: fixes for E2Es cleanup operations

- tests/e2e/tablespaces_test.go
- tests/labels.go
Also add a new label for Tablespaces tests
> fix: Order tests label in alphabetical order

- .github/workflows/continuous-delivery.yml
> ci: alert systematic failures only from main or release branches

- pkg/management/barman/capabilities/detect.go
This patch adds meaningful log messages to the capabilities detection process.
Given the pure technical scope and the size, no issue is attached to this PR.
> chore: improve logging in barman-cloud capability detection

- .github/workflows/continuous-integration.yml
Remove the repo restriction of Snyk run on the CI
Closes #4023
> chore: remove unneeded restrictions

- docs/src/cloudnative-pg.v1.md
In a previous PR we merge some issues with the documentation.
> fix: fixing documentation

- controllers/cluster_controller.go
- pkg/reconciler/instance/metadata.go
- pkg/reconciler/instance/metadata_test.go
- pkg/reconciler/persistentvolumeclaim/metadata.go
- pkg/reconciler/persistentvolumeclaim/reconciler.go
- pkg/reconciler/persistentvolumeclaim/reconciler_test.go
- pkg/reconciler/persistentvolumeclaim/resources_test.go
- pkg/reconciler/persistentvolumeclaim/suite_test.go
> fix: Make sure pvcs have correct value of the label `instanceRole`  and 'Role'

- docs/src/connection_pooling.md
> docs(pooler): clarify that `user_search` requires `superuser`

- api/v1/pooler_types.go
- config/crd/bases/postgresql.cnpg.io_poolers.yaml
- controllers/pooler_controller_test.go
- docs/src/cloudnative-pg.v1.md
- docs/src/connection_pooling.md
- docs/src/samples/pooler-basic-auth.yaml
- internal/management/controller/instance_controller.go
- tests/e2e/fixtures/pgbouncer/pgbouncer-pooler-basic-auth-ro.yaml
- tests/e2e/fixtures/pgbouncer/pgbouncer-pooler-basic-auth-rw.yaml
> fix: use fully-qualified objects in pooler integration queries

- docs/src/operator_conf.md
- docs/src/ssl_connections.md
- internal/configuration/configuration.go
- pkg/certs/certs.go
- pkg/certs/certs_test.go
- pkg/configparser/configparser.go
- pkg/configparser/configparser_test.go
Allowed the configuration of certificationDuration and expiringCheckThreshold parameters.
Closes: #1691
> feat: allow configuration of certificate duration and expiring check time

- .wordlist-en-custom.txt
- docs/src/release_notes/v1.21.md
- docs/src/release_notes/v1.22.md
- docs/src/supported_releases.md
> docs: Release notes for 1.22.2 and 1.21.4

- .github/k8s_versions_scope.json
> chore: enable unit tests on Kubernetes 1.29

- hack/setup-cluster.sh
Since the new version is way ahead of what we had we also updated the configuration method and removed the old way to do it. Now it uses annotations to detect what it needs to be scrapped
Closes #3872
> chore: update the pyroscope version

- tests/e2e/asserts_test.go
- tests/e2e/fixtures/backup/minio/cluster-with-backup-minio-legacy.yaml.template
- tests/e2e/fixtures/upgrade/cluster1.yaml.template
- tests/e2e/fixtures/upgrade/cluster2.yaml.template
- tests/e2e/fixtures/upgrade/scheduled-backup.yaml
- tests/e2e/upgrade_test.go
- tests/e2e/volume_snapshot_test.go
- tests/utils/minio.go
> test: fix backup and restore e2e test case failure

- .github/workflows/release-publish.yml
This will allow any user to use the bundle easily without waiting for this to be published in OperatorHub.io
Closes #4038
> feat: publish the OLM bundles in the artifacts directory (#4039)

- .github/workflows/release-publish.yml
> ci: fix the publish of OLM bundles

- internal/cmd/plugin/status/status.go
> fix(plugin): percentage in physical backup progress

- Dockerfile
> chore: update the base image for the operator

- .github/renovate.json5
- hack/setup-cluster.sh
> chore: add external CSI components and rook to Renovate

- docs/src/labels_annotations.md
> doc: improve instanceRole, podRole and role definitions

- .github/workflows/continuous-delivery.yml
> fix: using right tag for UBI8 image during e2e

- .github/renovate.json5
- .github/workflows/continuous-integration.yml
- Makefile
> test: add openshift-preflight tests to the CI

- .github/workflows/continuous-integration.yml
- .github/workflows/release-publish.yml
- .goreleaser.yml
> chore: add SBOMs for the operator container images and archive builds

- internal/cmd/plugin/status/status.go
> feat: add PDB to the plugin `status` command

- docs/src/installation_upgrade.md
- docs/src/release_notes/v1.23.md
> fix(docs): Add user-defined replication slots to the 1.23 release

- docs/src/container_images.md
> docs: fix minor editing error in container images doc

- docs/src/release_notes/v1.23.md
> docs: Release notes for 1.23.1

- internal/management/controller/instance_controller.go
> fix: log private key changes in refreshCertificateFilesFromSecret

- tests/e2e/asserts_test.go
> tests: do not verify pg_stat_bgwriter metrics in v17
