.github/workflows/chatops-receiver.yml

fix: add missing `}` in chatops-receiver workflow

---

internal/cmd/manager/instance/run/cmd.go
internal/cmd/manager/instance/run/lifecycle/reaper.go
pkg/management/postgres/pidfile.go

This patch adds a Runnable to the instance manager, which will reap any
postgresql orphaned process. This will address the syslogger processes
orphaned after in-place restarts or fencing.
Signed-off-by: Philippe Scorsolini <philippe.scorsolini@enterprisedb.com>
Closes #45

feat: reap postgres orphaned processes

---

docs/src/backup_recovery.md
docs/src/postgresql_conf.md
pkg/postgres/configuration.go

Make the `archive_timeout` setting configurable, with a default and
recommended value of 5 minutes.
Closes #86

feat: allow configuration of `archive_timeout` setting

---

CONTRIBUTING.md

fix: use invitation link for Slack

---

internal/management/controller/cache.go
internal/management/controller/instance_controller.go

It could happen that the RBAC for the secrets needed by backup could not yet be created during an instance manager reconciliation loop, this would generate a `forbidden` error type that was ignored by the process leaving the instance manager cache in an inconsistent state.
To avoid being stuck in an inconsistent state we queue a new reconciliation loop if the error is encountered.
This PR also includes a better organization of the cache reconciliation logic.
closes #85 

fix: triggers a renconciliation loop if the RBAC for backups is not yet created

---

.github/workflows/registry-clean.yml

Clean up the older images in testing packages (packages name ends with `-test`), using scheduled workflow. 
Closes: https://github.com/cloudnative-pg/cloudnative-pg/issues/121
Signed-off-by: Tao LI [tao.li@enterprisedb.com](mailto:tao.li@enterprisedb.com)

ci: clean up older images from testing package

---

pkg/management/postgres/probes.go
pkg/management/postgres/webserver/metricserver/pg_collector.go

We retrieve the values of pg_stat_wal and expose them as metrics if the instance version of Postgres is >=14
closes #54

feat: adds pg_stat_wal metrics

---

.github/workflows/continuous-delivery.yml
.github/workflows/release-publish.yml
.goreleaser.yml

Now we build for ARMv8 (arm64) and ARMv7(arm) the operator manager, this
means that we can start the basic support for ARM architectures.
Closes #159 

feat: add support for ARMv8 and ARMv7

---

pkg/management/postgres/instance.go
pkg/management/postgres/logpipe/logpipe.go

This patch ensures that we can collect the Postgres log files when we start the instance with the WithActiveInstance function.
It does that by starting a CSV logpipe process with the instance and terminating it before terminating the WithActiveInstance function.
Closes #130

fix: enable CSV logpipe inside WithActiveInstance function

---

docs/README.md

doc: use minidocks/mkdocs image for mkdocs build and serve commands

---

tests/e2e/asserts_test.go

this code is necessary to reduce drift with the CNP repo.
There we have the webhook test failing massively in the nightly builds,
and is not reproducible neither locally nor on the feature branch.
This code will show which validation(s) are failing

test: display the validation errors in the webhook test

---

controllers/replicas.go
pkg/utils/operations.go
pkg/utils/operations_test.go

Now when labels or annotations are updated from cluster `spec.inheritedMetadata`
pod will reflect the change without a restart. 
Closes #163
Signed-off-by: tao <tao.li@enterprisedb.com>

fix: inherit labels/annotations from cluster without restart pod

---

.github/workflows/release-publish.yml

During the release process now we add the YAML file used to deploy
the operator in a vanilla Kubernetes, this is to provide an easy way
to find the YAML file for any user or external application that may
want to access the release YAML file.
Closes #201

chore: add the release file to artifacts

---

.github/workflows/chatops-dispatcher.yml
.github/workflows/continuous-delivery.yml
.github/workflows/require-labels.yml

Adds an emoji to the "ok to merge" label, the `:ok_hand:` just to
improve the visual on the PR list.

chore: improve "ok to merge" label

---

controllers/cluster_upgrade.go
internal/management/controller/instance_controller.go

Now when sensitive param like `max_connection` is decreased, 
fixed the problem that sometime switchover will happens. 
Closes https://github.com/cloudnative-pg/cloudnative-pg/issues/168
Signed-off-by: tao <tao.li@enterprisedb.com>

fix: sensitive param decrease should not leads to switchover

---

tests/e2e/backup_restore_test.go
tests/e2e/fixtures/backup/cluster-from-restore-custom.yaml
tests/e2e/fixtures/backup/minio/backup-minio-custom-servername.yaml
tests/e2e/fixtures/backup/minio/cluster-with-backup-minio-custom-servername.yaml.template

adds E2E test to verify the patch fixing the recovery from a cluster
with a custom `serverName` in the backup configuration
Closes https://github.com/cloudnative-pg/cloudnative-pg/issues/220

test: add e2e test for recovery with custom serverName

---

.github/postgres-versions-update.py

The old regexp used to detect the version was only accepting versions
in the format `major.minor-revision`, now we also accept the format
with the beta `major(alphaN|betaN|rcN)-revision`
Closes #103

chore: add support for alpha, beta and rc images

---

controllers/cluster_controller.go
controllers/cluster_create.go
controllers/cluster_status.go
controllers/cluster_upgrade.go
docs/src/fencing.md
pkg/management/postgres/probes.go
pkg/postgres/status.go
pkg/postgres/status_test.go

With this patch we push down the fencing condition, so that fencing a
single instance will not anymore imply the whole cluster being fenced.
This way if a follower instace is fenced, in case of falure of the
primary instance, failovers will still be performed. In case of
deletion of a fenced instance, the pod will be recreated, relabelled
according to the previous role and if it was a primary instance, the
operator will not perform a failover as before.
Closes #44

feat: fencing limitation removed

---

.github/workflows/latest-postgres-version-check.yml

After we added the posibility to test alpha, beta and rc versions of
PostgreSQL, we also modified the script that updates the latest stable
version of PostgreSQL in the operator, this patch fix that by
excluding any alpha, beta or rc version from the list used to compare.
Closes #239

fix: use only stable release to change version

---

.github/workflows/pr_verify_linked_issue.yml

A new action to check that every PRs contains a linked issue, the idea
is to avoid having PRs without a proper linked issue.
Closes #178 

chore: add a verification issue link verification

---

docs/src/architecture.md

Replacing the reference and link to BDR with reference and link to
EDB Postgres Distributed (pgd) because of the name-change at EDB.
Closes #261
Signed-off-by: Jan Karremans <jan.karremans@enterprisedb.com>

doc: update architecture.md file

---

internal/cmd/manager/walrestore/cmd.go
pkg/management/barman/backupdelete.go
pkg/management/barman/backuplist.go
pkg/management/postgres/backup.go
pkg/management/postgres/restore.go

Remove `-e` parameter not existing in most barman commands and fix ambiguous `--encrypt`
Closes #218
Signed-off-by: Francesco Canovai <francesco.canovai@enterprisedb.com>

fix: correct encryption parameters in Barman commands

---

docs/src/cnpg-plugin.md
internal/cmd/plugin/report/deployments/deployments.go
internal/cmd/plugin/report/operator_objects.go
internal/cmd/plugin/report/operator_report.go

The fix includes two parts:
1. Reduce the times of function call for operator report function
2. Continue search operator deployment from user namespace
Closes #247  

fix: search operator deployment from user namespace

---

internal/cmd/plugin/status/status.go
pkg/management/postgres/probes.go
pkg/postgres/status.go

Sort the results of `Certificates Status` and `Streaming Replication status`
before printing per `status` command of cnpg plugin.
Closes: #170 

fix: sort results before printing in cnpg status plugin

---

docs/src/logging.md
docs/src/postgresql_conf.md

Add clarity that log storage is not in the purview of cnpg.
Closes #290 

docs: clarify log storage is not in operator

---

.github/workflows/continuous-delivery.yml

This fix reduce the chance of e2e test automatically run. for push event, 
e2e test will only automatically run on main and dependabot/** branch. 
For pull request event, e2e test case will only automatically run when 
event type is opened. 
Closes #256 

ci: remove automatically e2e test run for push and pull request

---

.github/workflows/continuous-delivery.yml

Reverts cloudnative-pg/cloudnative-pg#257
I reverted because with this comment is impossible to merge any PR due to the lack of required testing steps.

Revert "ci: remove automatically e2e test run for push and pull request"

---

api/v1/cluster_webhook.go
controllers/cluster_controller.go
controllers/cluster_status.go

The part of pull request #198 regarding the upgrade from a version
setting reasons containing space is wrong because it is impossible to
update the status in a defaulting webhook or with a simple Update
call. Moreover, the setDefault function misses the difference because
it only compares the content of the spec section.
In most cases, the previous code works anyway because the Cluster
reconciliation loop must update the status after an operator
upgrade. However, in rare cases, it could lead to a cluster that is
impossible to upgrade.
This patch fixes the issue by moving the upgrade code from the webhook
to the main controller reconciliation loop.
Closes #329

fix: version upgrade logic in patch #198

---

controllers/cluster_status.go

Avoid race condition if two patch is applied in one reconcile loop
Closes #335 

fix: avoid two patch in one reconcile loop

---

docs/src/release_notes.md

doc: improve release notes for the `withActiveInstance` logging patch

---

api/v1/cluster_configuration.go

fix: only healthy pods are electable as synchronous replica

---

api/v1/cluster_types.go
docs/src/monitoring.md
internal/management/controller/instance_controller.go

This patch enables CNPG to execute monitoring queries against the
application database for replica clusters, bootstrapped with the
`pgbasebackup` and the `recovery` bootstrap method.
We are fixing the behavior of `GetApplicationDatabaseName` too, directly
getting the database name (and owner) regardless of whenever the
application database need to be created or not.
Closes #345

fix: support application database monitoring for replica clusters

---

pkg/management/postgres/instance.go
pkg/management/postgres/pidfile.go
pkg/management/postgres/pidfile_test.go

We weren't testing the positive case in our unit tests, that is when the
`postmaster` process actually exists.
In order to do that, the implementation of `CheckForExistingPostmaster`
had to be changed to allow the code to inject a custom process name.
Closes #369

test: CheckForExistingPostmaster implementation easier to test

---

tests/e2e/fixtures/metrics/custom-queries.yaml
tests/e2e/metrics_test.go

This PR has been fixed following issues in metrics collection tests:
- `semantic version` range to limit the versions of PostgreSQL to run query on (`>=10.0.0`) in custom query configMap file.
-   regex keyword value length fix from `8 to 9` in metrics E2E. 
Closes: #366
Closes: #365 

fix: e2e in metrics collection with runonserver query created by user

---

pkg/versions/versions.go
tests/utils/version_test.go

When the default image cannot be pulled, this should result
in a clear alert.
Closes #397 

ci: early warning on bad DefaultImage

---

api/v1/backup_types.go
api/v1/scheduledbackup_types.go
controllers/scheduledbackup_controller.go

This patch removes GetKubernetesObject method from the codebase.
This was used to normalize the data coming from apiv1beta1 and apiv1 structs.
Given that we removed apiv1beta from the codebase this is not anymore needed.
Closes #379 

refactor: removes GetKubernetesObject method

---

pkg/management/postgres/metrics/collector.go

If `rows.Err()` returns a non nil error, the log tries to call `err.Error()` on the wrong `err` that might be nil causing a nil pointer dereference and crashing the whole controller.
Closes #395

fix: collector panic when query rows returns a non nil error

---

pkg/management/postgres/logicalimport/database.go

We where missing the `-U` argument for the pg_restore while running
importing the database from a file.
Closes #410 

fix: use `postgres` user while running pg_restore

---

hack/release.sh

make release script update the operator manifest url to current  
branch name
Closes #383 

chore: update operator manifest version in release script

---

docs/src/postgresql_conf.md
pkg/postgres/configuration.go

Up to now, `huge_pages` was a blocked configuration option for PostgreSQL
and users were not allowed to change it. We have removed this block,
leaving the option to the default value defined by the PostgreSQL server
in the operand images (normally at compile time).
Closed #428

feat: enable configuration of `huge_pages` for PostgreSQL

---

tests/e2e/upgrade_test.go

In the upgrade E2E tests, we get the latest WAL with two combined
commands: `CHECKPOINT; SELECT pg_walfile_name(pg_switch_wal())`
In Postgres15, by default all query command outputs are shown.
See https://github.com/postgres/postgres/commit/3a5130672296ed4e682403a77a9a3ad3d21cef75
When we then create a CLI string to check the last WAL file, the output
contains more than just the WAL number, and this breaks the construction
of the `minio` path for the test.
We fix this  by using the setting `SHOW_ALL_RESULTS=off`
Closes #420 

fix: get latest WAL correctly for Postgres 15 in upgrade E2E test

---

.github/workflows/latest-postgres-version-check.yml

After fixing the detection of the pre-release PostgreSQL version
we forgot to add the install of one of the new packages required,
this package is `packaging`.
Closes #483 

fix: add missing package `packaging`

---

.github/summarize-test-results.py
.github/workflows/continuous-delivery.yml

Adds a step to the CI/CD pipeline summarizing the results of the
E2E tests. We already have a step in each "strategy matrix" branch
to create and upload a JSON artifact file per test executed.
This code collates all the artifacts and creates a Markdown
summary for display in GitHub Actions.
Closes #189 

ci: E2E test summary step

---

pkg/podspec/builder.go
pkg/specs/jobs.go
pkg/specs/pgbouncer/deployments.go
pkg/specs/pods.go
pkg/specs/pods_test.go

This patch ensures that the generated Pooler deployment has the securityContexts populated
Closes #479

fix: ensures that the Pooler deployment has the securityContext populated

---

.github/e2e-matrix-generator.py
.github/workflows/chatops-dispatcher.yml
.github/workflows/continuous-delivery.yml

We introduce a new behaviour in this commit:
1.- The commits now can run in the forked repo, using the external
user registry to push the image and the run the E2E.
2.- A new command `ready-to-test` that use the `pull_request_target`
event to run the test and run the E2E test on the PR, this will
allow the forked repo to run test from the PR when a user allows it.
Previously we were not able to run the E2E on PR from forked repo
due to the fixed use of the cloudnative-pg repo and since the
`pull_request` event doesn't provide a GitHub token with write permissions
for packages.
We still allow running E2E test from internal branch only when the `test`
command is used, since it will trigger the event dispatch with the client
payload and is used to verify that comes from the internal repo. …

feat: add ready-to-test command and independent container registry

---

pkg/certs/k8s.go

In the `injectPublicKeyIntoCRD` function, the TLS cert is always
injected into the CRD conversion webhook. This can produce
conflicts with concurrent updates to the CRD.
This code ensures the update is only done when the TLS cert
is out of date, and includes a retry.
Closes #499 

fix: avoid updating CRD if TLS cert unchanged

---

.github/workflows/continuous-delivery.yml

Running the continuous-delivery workflow on a release-* branch must
skip the detection of what changed in the last commit and run all the
tests, as it does on the main branch.
Closes #505 

ci: support running full E2E tests on release-* branches

---

api/v1/cluster_types.go
internal/management/controller/instance_controller.go
pkg/utils/time.go
pkg/utils/time_test.go

This patch adds a new method for `cluster` that logs timestamp information to stdout, and uses it to log this information during the switchover, failover and demotion of a primary instance
Partially Closes #57
E2E tests will be handled by a different PR

feat: adds logs during switchover, failover and demotion

---

internal/cmd/plugin/fence/fence.go

This patch fix the panic if fencing a cnp pod when cnp cluster 
has no annotation.
Closes #511 

fix: avoid panic while fencing postgres if cluster has no annotation

---

pkg/utils/time.go
pkg/utils/time_test.go

This patch switches RFC3339Nano to the same RFC3339Time given that is used by metav1.MicroTime
Closes #503 

chore: set timestamps to RFC3339Micro

---

api/v1/cluster_webhook.go
api/v1/cluster_webhook_test.go

This patch removes a duplicate webhook aimed at the storage size validation
Closes #514

chore: remove redudant storage validation webhook

---

internal/cmd/manager/instance/run/lifecycle/lifecycle.go

This patch fix the timeouts that we were using during a restart and
during switchovers to use the right fields in the Cluster specification.
Closes #530

fix: timeouts for restarts and switchovers

---

docs/src/ssl_connections.md
tests/e2e/fixtures/fastfailover/webtest-syncreplicas.yaml
tests/e2e/fixtures/fastfailover/webtest.yaml
tests/e2e/fixtures/fastswitchover/webtest.yaml
tests/utils/webapp.go

The project webtest was migrated to the cloudnative-pg organization and
so was the registry, this patch aims to point the image to the new
location in ghcr.io
Closes #532

chore: use the new webtest location

---

.wordlist-en-custom.txt
api/v1/cluster_types.go
controllers/cluster_status.go
docs/src/troubleshooting.md
tests/e2e/asserts_test.go
tests/e2e/cluster_setup_test.go
tests/utils/cluster.go

This PR has introduces cluster conditions and adding cluster is ready or not in cluster status like:
```
status:
conditions:
- lastTransitionTime: "2022-07-22T10:03:02Z"
reason: ClusterIsReady
status: "True"
type: Ready
message: Cluster is Ready
- lastTransitionTime: "2022-07-22T10:02:02Z"
reason: ClusterIsNotReady
status: "False"
type: Ready
message: Cluster Is Not Ready
```
Closes #84  

feat: set cluster condition ready when the phase is healthy

---

tests/e2e/asserts_test.go
tests/e2e/fastfailover_test.go
tests/e2e/fastswitchover_test.go
tests/e2e/fixtures/fastfailover/apache-benchmark-webtest.yaml
tests/e2e/fixtures/fastswitchover/apache-benchmark-webtest.yaml

The project hey is not building multiarch images which makes complicated
to test in different archquitectures. Now using Apache benchmark we will
have different architectures available in the httpd image from Docker Hub.
Closes #536

chore: use Apache benchmark instead of hey

---

config/manager/manager.yaml

After running trivy to diagnose the operator deployment we found a couple
of security issues fixed here:
* securityContext.capabilities.drop: ALL
* securityContext.runAsNonRoot: true
* securityContext.runAsUser: 10001
* securityContext.runAsGroup: 10001
* securityContext.seccompProfile.type: RuntimeDefault
All of these issues are fixed in the manager deployment and will not affect
the code itself.
Closes #541

chore: improve operator deployment security

---

hack/show-release-diffs.sh

This helper script must be run inside a release branch and reports
in Markdown format the pull requests the are not present in both
branches. This hopefully will help maintainers keep track of which
commits to backport, while waiting for an automated mechanism
that, once a commit is merged in main, issues a PR on each requested
release.
Closes #552

chore: add basic script to report diffs release branch <-> main

---

pkg/certs/k8s.go

Add `RetryOnConflict` in func `injectPublicKeyIntoValidatingWebhook` and `injectPublicKeyIntoMutatingWebhook` to retry updating in case of conflict failures.
Closes #546 

fix: use `RetryOnConflict` to update resources

---

controllers/cluster_create.go
controllers/suite_test.go
pkg/specs/jobs.go
pkg/specs/pods.go
pkg/specs/pvcs.go
pkg/utils/labels_annotations.go

This patch adds the instanceName label and clusterName to several resources. 
This will help us to interact with them in an easy manner both inside our codebase and outside.
Closes #520 
Notes:
- This patch does not aim to address the issue of 'how' we want to patch the existing resources on previous version clusters. I think this is a different topic that deserves an ad hoc discussion.

chore: adds instanceName and clusterName labels on jobs, pods, pvcs

---

pkg/management/external/utils.go

This patch allows the developer to specify the directory where the external cluster secrets will be saved.
This is needed to allow the unit testing of certain external cluster methods.
Closes #559
As discussed with @jsilvela  @gbartolini  and @jlong49  this is a temporary fix until we properly refactor the whole chain call of functions

refactor: allows the override of the default external secret directory

---

docs/src/database_import.md

Due to CloudNativePG using the lib/pq library in Go that doesn't support
`sslmode=prefer`, we document that in the `monolith` import we must
explicitly specify the value of `sslmode`. This behaviour will be
fixed in the future by replacing lib/pq with another library.
Closes #392

doc: mention `sslmode: disable` in `monolith` import

---

hack/setup-cluster.sh

Using the existing script `hack/setup-cluster.sh` to create the testing cluster
we should also use the existing functions `load_image_(kind|k3s)` to pre-load
the helper images needed by the test, this aim to improve the test speed.
Closes #574

chore: pre-load helper images in testing cluster

---

.github/workflows/release-publish.yml

We were publishing to the krew-index every release, we should just do it
wen we're in the latest release branch.
Closes #601 

chore: skip Krew release if not the latest

---

api/v1/pooler_webhook.go

Adding TCP parameters to allowed configurable parameters on webhook per discussion topic.  https://github.com/cloudnative-pg/cloudnative-pg/discussions/563  Please let me know if anything needs changed or added.

feat: allow configuring log-level TCP parameters for PgBouncer

---

hack/setup-cluster.sh

In our testing script `hack/setup-cluster.sh` we had a fixed value
for the `amd64` architecture instead of detecting the architecture and
use it to download the necessary tools.
Closes #566

chore: support multiarch for testing

---

pkg/specs/pvcs.go

This patch adds again a lost in transition label on the instance PVC.
Closes #633

chore(pvc): adds instance name label on the instances pvc

---

pkg/management/postgres/utils/utils.go

If `tx.Query` fails and returns a non nil error, rows will be nil and the deferred func will panic because rows is nil.
#640

fix bug in GetAllAccessibleDatabases where a failed query triggers a panic

---

tests/e2e/suite_test.go
tests/e2e/wal_restore_parallel_test.go
tests/utils/backup.go
tests/utils/commons.go
tests/utils/environment.go
tests/utils/run.go

Before we were having only one `RetryTimeout` for the API calls and for
the commands execution, nonetheless, we need a different value for commands
since these can fail quicker and API calls.
This will fix any test that was waiting one minutes before even start a
retry.
Closes #580

chore: split retry timeout for client and commands

---

.github/summarize-test-results.py
.github/summarize_test_results.py
.github/workflows/continuous-delivery.yml
tests/e2e/initdb_test.go

Improve the E2E Summary Step:
1. Add a timing table with max / min time taken per test, sorted by slowest
2. Add tables bucketing the results by K8s version, PG version, platform
3. Add rows to the overview for failed vs total K8s versions, PG versions, platforms
5. Add a navbar, and clarify that we have several tables
Closes #548 

feat: refine stats in E2E summary

---

pkg/management/postgres/initdb.go
pkg/management/postgres/instance.go

This change makes `postInit*SQL` run on a instance with loaded additional libraries, which comes handy for `CREATE EXTENSION`  commands which can use features provided by additional libs.
Fixes: https://github.com/cloudnative-pg/cloudnative-pg/issues/649

Load additional libraries when initializing database

---

hack/setup-cluster.sh

We were creating loading the helper images only when running in a local
run, this wasn't considering when running in the E2E tests, this will
fix that by loading the helper images during the cluster creation.
Closes #652

chore: load helper images during cluster creation

---

.github/summarize_test_results.py

This patch unhidden the "failed test summary table" in e2e test summary page
and correct some order of the table headers. 
Closes #662 

test: display failed test summary table

---

pkg/management/upgrade/upgrade.go

Avoid using an hardcoded file name to store the newly uploaded
instance manager, preventing a possible race condition to happen.
Closes #659

fix: use a temporary file to host the new instance manager binary

---

controllers/cluster_controller.go
controllers/replicas.go

This patch ensures that the labels:
- `"cnpg.io/instanceName` is present on both PVCs and instance pods
- `"cnpg.io/podRole"` on the instance pod
are correctly reconciled during the `reconcileResources` phase.
This will make sure that:
- those labels will be eventually present on  the pods and pvcs created on previous versions
- in case of accidental deletion they will be readded by the operator
Closes #679

chore: ensure that `cnpg.io/instanceName` and `cnpg.io/podRole` are correctly reconciled on existing resources

---

pkg/utils/db.go

Setting the default datestyle variable for the PostgreSQL connection
helps to keep a known standard when parsing dates from the database.
Closes #694

fix: Set the default datestyle to ISO

---

pkg/management/postgres/compatibility/doc.go
pkg/management/postgres/compatibility/unix.go
pkg/management/postgres/compatibility/windows.go
pkg/management/postgres/instance.go

The call to `Setpgid` would prevent us from compiling the plugin for windows architecture.
This patch ensures that we do not call `Setpgid` while compiling for windows.
Closes #699

fix: do not invoke `Setpgid` while compiling for windows architecture

---

tests/e2e/asserts_test.go
tests/e2e/fixtures/replication_slot/cluster-pg-replication-slot.yaml.template
tests/e2e/replication_slot_test.go
tests/utils/cluster.go
tests/utils/replication_slots.go

First implementation of the E2E for replication slots.
E2E tests for #8.

tests: Add E2E for replication slots

---

pkg/postgres/configuration_test.go

The latest version of ginkgo highlighted a parenthesis misplacement
in one of our unit tests.
Closes: #747 

test: fix misplaced parenthesis in unit tests

---

internal/management/controller/instance_controller.go
pkg/management/postgres/instance.go

This patch drops all the connections made before the standby promotion are dropped.
Closes #736

fix: ensures that the promoted standby active connections are dropped after promotion

---

api/v1/cluster_types.go
controllers/cluster_controller.go
controllers/cluster_status.go
internal/cmd/manager/walarchive/cmd.go
pkg/management/postgres/backup.go
pkg/utils/conditions.go

This patch cherry-picks the PR containing the logic needed to sanitize the cluster conditions
Closes #719 

fix: ensure that the conditions contained in the cluster status are made compatible with metav1.Conditions struct

---

internal/cmd/manager/controller/cmd.go
internal/cmd/manager/controller/controller.go

This patch makes it possible to customize `leaseDuration` and `renewDeadline` in the controller manager.
Closes #758

chore: enables the customization of leaseDuration and renewDeadline in the controller manager

---

.github/workflows/codeql-analysis.yml
.github/workflows/continuous-delivery.yml

The `pull_request_target` it's not a possible value for skip-duplicate-actions

fix: wrong action in the `do_not_skip` section

---

go.mod
go.sum

The library golang.org/x/net was affected by CVE-2022-27664, this patch updates the version to avoid being affected by that bug.
Closes #812

security: update golang.org/x/net version 

---

hack/e2e/run-e2e-k3d.sh
hack/e2e/run-e2e-kind.sh
hack/setup-cluster.sh

Added a new command to the `setup-cluster.sh` script that will load the helper images instead of loading the images by default.
This fix will avoid loading images everytime in some systems.
Closes #804

fix: create load-helper-images command for setup-cluster.sh

---

.github/generate-test-artifacts.py
tests/e2e/nodeselector_test.go

Enhances the Test Summary to capture as failures the cases where
a matrix branch fails before getting to the E2E execution.
This way the failed branches reported by the Summary should match GitHub
Closes #791

ci: reflect failing CI branches in Test Summary

---

.github/workflows/continuous-delivery.yml

`CONTROLLER_IMG` need to be set in `generate-manifest` in case the value can't be correctly inferred when the branch name of the PR can't be parsed from the SHA value.

fix: add the operator image env

---

controllers/cluster_controller.go
controllers/cluster_restore.go
internal/cmd/plugin/hibernate/cmd.go
internal/cmd/plugin/hibernate/off.go
internal/cmd/plugin/hibernate/resources.go
pkg/specs/jobs.go
pkg/specs/pods.go
pkg/specs/pvcs.go

This patch Introduces the `hibernate off` command and the needed reconciliation logic, which restores the cluster resource starting from the hibernated primary instance PVC Group.
You can reactivate a cluster with:
```
kubectl cnpg hibernate off <cluster-name>
```
This will:
1. fetch the hibernated PVC Group and select one of them (if multiple PVCs were created for a single instance)
2. extract the cluster manifest from the  `cnpg.io/hibernateClusterManifest` PVC annotation
3. clean the cluster manifest from any runtime data.
4. create the cluster resource 
5. the operator will detect the freshly created cluster having orphan PVCs
6. the operator will reassign the existing PVC to the cluster and recreate the primary instance
A future commit will implement the `hibernate status` command to …

feat: adds hibernate off

---

docs/src/cnpg-plugin.md
internal/cmd/plugin/hibernate/cmd.go
internal/cmd/plugin/hibernate/output.go
internal/cmd/plugin/hibernate/status.go
internal/cmd/plugin/printer.go

This patch Introduces the `hibernate status` command, which reports the cluster hibernation status. 
It supports two outputs:
- `text`, which prints the hibernation status to stdout.
- `json` which outputs the data in a json format. This mode also supports the `--file` or `-f` flag to indicate in which `path/file` the generated json should be put, if not specified it prints the json in stdout. 
You can print the cluster hibernation status with:
```
kubectl cnpg hibernate status <cluster-name>
```
The command can detect three different statuses:
- The cluster already exists.
- The cluster doesn't exist and the PVC is hibernated.
- Neither the cluster nor the hibernated PVC exists.
Closes #789

feat: adds hibernate status command

---

pkg/specs/podmonitor.go
pkg/specs/podmonitor_test.go

This patch makes sure that we avoid writing directly the `ClusterLabelName` annotation inside the CreatePodMonitor method. This removes the duplicated ClusterLabelName annotation writing logic.
Partially Closes #837

chore: ensures that `CreatePodMonitor` uses `LabelClusterName`

---

tests/utils/commons.go

we were using the RetryDelay (60) as the NUMBER of retries

fix: use the right constant for retry logic in tests

---

contribute/README.md

Pass the URL of the manifest instead of using `curl` in the example included in the contribution guide.
Closes #898

doc: cosmetic change to snapshot testing documentation

---

tests/utils/minio.go

The home location for minio changed, change the certification location 
accordingly for e2e test. 
closes: #909 

test: change minio client self-signed certification location in test case

---

controllers/scheduledbackup_controller.go
pkg/management/postgres/backup.go
pkg/management/postgres/initdb.go

We require WAL archiving to be working before taking every backup, and we control that by checking the archival status of the latest archived WAL.
For this check to pass, we need to have a WAL to archive, which is not always true for new clusters.
For PostgreSQL 14 and older, this condition was granted by the `archive_timeout` setting, but since PostgreSQL 15, the instance won't mark the first WAL as ready to archive if there is no database activity.
With this patch, we switch to a new WAL when a backup is requested, and Postgres never attempted archiving a WAL file.
Closes: #896

fix: ensure we have a WAL to archive for every newly created cluster

---

controllers/cluster_controller.go
controllers/cluster_status.go
controllers/cluster_upgrade.go
controllers/cluster_upgrade_test.go
controllers/replicas.go
internal/plugin/resources/instance.go
pkg/postgres/status.go
pkg/postgres/status_test.go

The operator was relying on the readiness status of the Pod to determine if the current primary was healthy of not, but sometimes this will be different from the real PostgreSQL status since it's checked every `periodSeconds` by the Kubelet.
This can happen when lifting fencing from the primary node and the Kubelet still haven't marked the Pod as ready, leading for a failover to happen immediately after the event.
With this patch, we are using the status collected from the instance manager to elect the new primary, and we'll wait for the Kubelet to refresh the readiness probe status when PostgreSQL is up and running but the Pod is still marked as non ready.
Closes: #889

fix: avoid failovers when Pod readiness status is stale

---

pkg/utils/labels_annotations.go

chore: removes the unused constant:`ReconciliationDisabledValue`

---

.github/e2e-matrix-generator.py
.github/workflows/chatops-receiver.yml
.github/workflows/continuous-delivery.yml
.github/workflows/latest-postgres-version-check.yml
.github/workflows/release-publish.yml

This patch replace the deprecated set-output command used in workflow
with redirect the output to $GITHUB_ENV or $GITHUB_OUTPUT
closes: #874 

chore: replace deprecated set-output command in workflow

---

tests/utils/azurite.go
tests/utils/curl.go
tests/utils/minio.go
tests/utils/webapp.go

Setting RunAsNonRoot explicitly to false is not only redundant, but it could trigger errors.
Closes #922 
Co-authored-by: John Long <john.long@enterprisedb.com>

Avoid setting RunAsNonRoot to false explicitly

---

internal/cmd/plugin/hibernate/on.go
internal/plugin/resources/instance.go
pkg/utils/exec.go

This patch ensures that we rely only on the exit code to determine if an instance is stopped. 
This removes the previous behavior of checking the pg_ctl message which generated errors with languages different than English
Closes #934

fix(hibernate): evaluate `pg_ctl status` exit code to determine if an instance is running

---

pkg/utils/discovery.go
pkg/utils/discovery_test.go

When the reported minor version is not an integer (i.e. `21+`) the seccomp detection is failing and will prevent the operator from starting correctly.
Closes: #946
This patch makes that function more resilient.

fix: seccomp detection is failing when minor version is not an integer

---

pkg/management/postgres/logicalimport/database.go
tests/e2e/fixtures/cluster_microservice/cluster-base.yaml.template

Limit the extensions to be removed in the logical import bootstrap phase to the user-defined ones. This way, the default provided `plpgsql` extension is not dropped before the restore phase is started.
Closes #869
Closes #970

fix: correctly manage `plpgsql` in database import

---

hack/e2e/run-e2e.sh

When running E2E tests on a local kind cluster via `./hack/e2e/run-e2e.sh`, the script would exit abruptly in case FEATURE_TYPE is not set:
```
./hack/e2e/run-e2e.sh: line 122: FEATURE_TYPE: unbound variable
```
Avoid failing in case the variable is not set (all the tests will be executed in case FEATURE_TYPE is not specified at all or set to an empty variable). 
Also make the script print out the filters only if additional filters besides to default `!(upgrade)` have been defined.  

tests: avoid failures if FEATURE_TYPE is not set

---

.github/workflows/latest-postgres-version-check.yml

The regexp replacing the previous-latest version with the new one was updating not related versions, like the CNPG version 1.15.0 to 1.15.1
The regexp is now more precise and only updates places where a space or a colon character precedes the Postgres version.
We also exclude all the versions in the release notes.
Closes #997

fix: automatic PostgreSQL version update regexp

---

.github/workflows/continuous-delivery.yml
docs/src/e2e.md

closes #1018 
Signed-off-by: Danish Khan <danish.khan@enterprisedb.com>

ci: removing unused rook env and k8s version 1.21 support from unit test

---

pkg/specs/services.go
pkg/specs/services_test.go

chore: replace `postgresql` with `cnpg.io/cluster` as service selector

---

controllers/cluster_controller.go
docs/src/monitoring.md
pkg/specs/poddisruptionbudget.go
pkg/specs/pods.go
pkg/specs/services.go

Some refactor has been done on how ports are created using only one function
for the ports in the service creation. 
Closes #1021

chore: centralize instance corev1.ServicePort generation logic

---

pkg/stringset/stringset.go
pkg/stringset/stringset_test.go

This patch instroduces a `stringset.Eq` method, which will be needed for the next commits.
Closes: #1069

feat: add `stringset.Eq` method

---

config/manager/env_override.yaml
internal/cmd/plugin/report/logs.go
pkg/utils/logs/logs.go
tests/e2e/asserts_test.go
tests/e2e/hibernation_test.go
tests/e2e/suite_test.go
tests/utils/cluster.go

To help investigate E2E test failures, we start tailing the operator
logs at the beginning of each spec, in a goroutine.
If the spec fails, we display the logs on Ginkgo and store them in a file.
Closes #960 

test: get operator logs on failed specs

---

docs/src/benchmarking.md
internal/cmd/plugin/pgbench/pgbench.go

- missing ApiVersion and Kind in pgbench manifest using --dry-run.
- Updating doc for NAMESPACE placement in pgbench under BenchMarking.
closes #1078
Signed-off-by: Danish Khan <danish.khan@enterprisedb.com>

fix:  missing ApiVersion and Kind in pgbench manifest using --dry-run and updating doc.

---

.github/k8s_versions_scope.json

Having 1.25 in the list of kubernetes version to test was producing
errors since this version it's not supported for this release 1.16
Closes: #1102 

chore: remove k8s version 1.25 from unit test and e2e

---

.github/k8s_versions_scope.json

Having 1.25 in the list of kubernetes version to test was producing
errors since this version it's not supported for this release 1.17
Closes: #1102 

chore: remove k8s version 1.25 from unit test and e2e in release

---

.github/workflows/chatops-dispatcher.yml
.github/workflows/chatops-receiver.yml
.github/workflows/continuous-delivery.yml
hack/e2e/env_override_customized.yaml.template

This patch make the operator log level configurable in e2e test suite, and 
expose the configuration into workflow dispatch and /test slash command options
Closes: #1086 

ci: Make the operator log level configurable in e2e test suite

---

.wordlist-en-custom.txt
CODEOWNERS
README.md

The group of maintainers has unanimously approved Armando Ruocco as a
new maintainer of CloudNativePG, based on the current criteria of nomination.

chore: Add Armando Ruocco (@armru) as a new maintainer

---

Makefile

Makefile was using a fixed container image to set as the default during the
deployment which was not doing any match with the default of the operator,
fixing this will align both the deployment default and the operator default
in the code.
Closes #916

chore: take PostgreSQL image from the pkg/versions/versions.go

---

internal/cmd/manager/bootstrap/cmd.go

Fixes: https://github.com/cloudnative-pg/cloudnative-pg/issues/625
I was able to confirm this fix is indeed working by forcing `0750` permissions on my PVC right after the bootstrap process started
Signed-off-by: Devin Buhl <onedr0p@users.noreply.github.com>

fix: permissions error on bootstrap

---

docs/src/troubleshooting.md

Integrate the troubleshooting section with instructions on how to take emergency
logical backups of the database, and restore on a new cluster.
Closes #1183

doc: provide troubleshooting emergency backup instructions

---

docs/src/bootstrap.md

I believe the documentation references "future" functionality that is fully implemented.
I have tested continuous recovery (replica clusters) from both pg_basebackup (streaming WALs) and barmanObjectStore. They both work as described in the documentation. As such, this paragraph should either be changed to refer to existing functionality and point to the replica clusters section, or removed entirely.

Remove docs reference to future functionality

---

controllers/cluster_controller.go

fixes the filtering applied to map nodes to CNPG clusters when a node
is cordoned, to create reconciliations only from primary instance pods
Closes #1193 

fix: filter out replicas and jobs from nodeToClusters map

---

api/v1/cluster_types.go
controllers/cluster_controller.go

Closes #1190 
Previously we were using the size of the main PVC to update the one dedicated to WAL storage. This led to "-wal" PVCs being created with the correct size at first, but then, in case the main PVC had a different size, to be resized to the main PVC's size.

fix: use correct size to update WAL PVC

---

internal/cmd/manager/instance/restore/cmd.go

Closes #1210.
We forgot to properly propagate the pg-wal flag's value, if any, down in the recover subcommand. This meant that primary instances created from backups were not actually using the volume dedicated to wal files, even if specified.

fix: respect configured pg-wal when restoring

---

go.mod
go.sum
hack/e2e/run-e2e.sh

The installation of ginkgo via `go install` is complaining about missing dependencies.
Those dependencies are not needed by our Go codebase. So, let's inject outside of go.mod.

fix: installation of ginkgo

---

go.mod
go.sum
hack/e2e/run-e2e.sh
internal/tools/tools.go

Puts back the file tracking ginkgo dependencies, which had been deleted.
With this, the `go get` instructions that were added when installing ginkgo
are no longer needed.
Closes #1224 

ci: track ginkgo deps in internal/tools/tools.go

---

tests/utils/environment.go
tests/utils/psql_client.go

Previously we were not detecting the SCC so if for some reason the 
Kubernetes cluster is using SecurityContextConstraints the `psql` pod
was going to fail since it will set a SecurityContext that shouldn't be there.

fix: adding the SCC checks to 1.17

---

controllers/cluster_create.go
docs/src/quickstart.md
docs/src/samples/cluster-example-monitoring.yaml

Since we know that the cluster doesn't have the option `enablePodMonitor` set to `true` there's no need to continue and ask every time to the Kubernetes API for this type of resource.
Closes #1212 

fix: don't look for PodMonitor when not needed

---

controllers/cluster_create.go

On PR https://github.com/cloudnative-pg/cloudnative-pg/pull/1213/
I over-fixed the logic, and can allow to proceed with the reconciliation
of PodMonitor, even if we know the Prometheus CRD are not installed

fix: avoid PodMonitor reconcile on no Prometheus

---

.github/workflows/continuous-delivery.yml
.github/workflows/continuous-integration.yml

Skip the smoke test on branch release-1.16 for 
v1.16 has been EOLed since December 21, 2022

ci: skip smoke test on EOLed version 1.16

---

.github/workflows/continuous-delivery.yml

We could label/unlabel the `ok-to-merge` not only
in the case of `issue_comment`

ci: fix the label/unlabel ok-to-merge precondition

---

.github/workflows/continuous-integration.yml
Makefile

- Add a check in the continuous-integration workflow to 
see if there's any dirty change for `go mod tidy`
- Also include the check in `make checks`
Closes #1273 

chore: check if there's any dirty change for go mod tidy

---

api/v1/cluster_types.go
api/v1/cluster_webhook.go
pkg/reconciler/persistentvolumeclaim/reconciler.go

This commit includes a refactor to validate the walStorage section
consistently with the storage one.
Closes: #1314 

fix: permit walStorage resize when using pvcTemplate

---

internal/cmd/plugin/install/generate.go

We added to new fields to the command line:
* --log-field-level
* --log-field-timestamp
Both used to change the respective values in the operator deployment.
Closes #1309

chore: add two new fields to the plugin install generation process

---

.github/workflows/continuous-delivery.yml

Fix unlabel-ok-to-merge step not working in ci/cd workflow
Close #1322  

fix: fix unlabel-ok-to-merge in workflow not work

---

cmd/kubectl-cnpg/main.go
docs/src/cnpg-plugin.md
internal/cmd/plugin/backup/cmd.go

The `kubectl cnpg backup` command allows to user to request an on-demand backup for a PostgreSQL Cluster.
Closes: #950
Signed-off-by: Leonardo Cecchi <leonardo.cecchi@gmail.com>

feat: add `backup` command to the `cnpg` plugin

---

docs/src/backup_recovery.md
docs/src/bootstrap.md

Mention that `postgresql.parameters` must be compatible from a physical
replication point of view with the backed up cluster.
Closes #1189

doc: note about postgresql.conf in `recovery`

---

api/v1/cluster_webhook.go
api/v1/cluster_webhook_test.go

This patch verify the postgres settings max_wal_size and min_wal_size with 
wal storage volume size. make sure. 
min_wal_size < max_wal_size < wal volume size
when min_wal_size and max_wal_size is not specified, default value will be considered
Close: #677  

fix: verify max/min wal size setting with wal storageSize

---

docs/src/monitoring.md
go.mod
pkg/management/postgres/metrics/collector.go
pkg/management/postgres/webserver/metricserver/pg_collector.go
pkg/management/postgres/webserver/metricserver/suite_test.go
pkg/management/postgres/webserver/metricserver/wal.go
pkg/management/postgres/webserver/metricserver/wal_test.go
pkg/utils/math.go

This feature provides more value for metrics cnpg_collector_pg_wal in default exporter, 
the goal is to provide an easy way to monitor the disk usage by relying on the WAL logic.
Closes: #1374 

feat: enhance cnpg_collector_pg_wal metrics for default exporter

---

docs/src/backup_recovery.md

Add `https://` scheme to the S3-compatible example for Linode.
Using a value without scheme here will result in a failure with a log message:
```
ERROR: Barman cloud backup exception: Invalid endpoint: s3.example.com
``` 
All the other sample `endpointURL`s on this page already have a scheme.

docs: add missing scheme for s3 endpoint example

---

.github/workflows/backport.yml
.github/workflows/continuous-delivery.yml
contribute/release_procedure.md

add the new minor release 1.19 to the backport workflow, and
clarify how to do this in the release documentation.

chore: add release 1.19 to backport workflow

---

.goreleaser.yml
Makefile

Added the new format of name_template to replace `replacements` during the archive process.
Added the new format in nfpms for `file_name_template`
Closes #1391

chore: Deprecate GoReleaser versions older than 1.14.0

---

Dockerfile

The old image gcr.io/distroless/static:nonroot has been deprecated and is no longer support, because of that we should use the new and supported image gcr.io/distroless/static-debian11:nonroot
Documentation https://github.com/GoogleContainerTools/distroless#what-images-are-available
Closes: #1508

chore: change distroless/static image for distroless/static-debian11

---

pkg/management/postgres/backup.go

Clarifies the backup retry code, avoiding the potential of variable shadowing.
Closes #1441

refactor: clarify the code to retry backups

---

pkg/specs/jobs.go

This patch enable the debug option for initdb process if the cluter.spec.logLevel is debug 
or more lower.
Closes: #1502 
Signed-off-by: Tao Li [tao.li@enterprisedb.com](mailto:tao.li@enterprisedb.com)

feat: enable debug option for initdb job

---

.goreleaser.yml
Dockerfile

The idea it's to add all the binary that support both architetures arm64 and amd64 to the operator container for future use in an experimental feature
Closes #1512

chore: add all the operator binary to the operator container

---

.github/generate-test-artifacts.py
.github/workflows/continuous-delivery.yml
tests/e2e/scaling_test.go

CIclops will ignore any JSON file that does not match the expected schema.
Two fields were missing in the "Report missing" artifacts, so they were ignored.

ci: ensure branches missing Gingko report are accounted

---

controllers/backup_controller.go

This patch ensure that each time when the backup encountered some error, the failed status
and reason are committed to the api server before next reconcile loop.
Closes #1535

fix: update the backup status in case of errors

---

controllers/cluster_upgrade.go
controllers/cluster_upgrade_test.go

Fix the issue that adding WAL storage to a cluster with a single instance
is not working
closes: #1527

fix: adding WAL storage to a cluster with a single instance is not working

---

pkg/management/postgres/backup.go
pkg/management/postgres/backup_test.go

This patch ensures that we always update the backup/cluster status in case of errors during the backup command execution.
Partially Closes #1523

fix: ensure backup command updates the resources status in case of errors

---

controllers/backup_controller.go
internal/cmd/manager/walarchive/cmd.go
pkg/conditions/conditions.go
pkg/management/postgres/backup.go

This patch ensures that we use Patch instead of Update to commit backup changes to the API server.
This avoids conflicts that could generate from divergent resourceVersion given that the backup resource is pooled by multiple reconciliation loops.
Partially closes #1523 

chore: use patch instead of update for Backup reconciler and command

---

pkg/management/postgres/backup.go

This patch ensures a reliable backup process by committing the completed backup changes during the takeBackup function instead of depending on the side effect of backupListMaintenance.
Partially Closes #1523

fix: commit the completed backup changes during takeBackup execution

---

.wordlist-en-custom.txt
internal/cmd/manager/instance/initdb/cmd.go
internal/cmd/manager/instance/join/cmd.go
internal/cmd/manager/instance/pgbasebackup/cmd.go
internal/cmd/manager/instance/restore/cmd.go
internal/cmd/manager/instance/run/cmd.go
internal/management/linkerd/doc.go
internal/management/linkerd/linkerd.go

Addresses the issue when the job's primary container is completed, while the pod which the Linkerd Proxy has injected in, won't be marked as completed since the sidecar keeps running.
Closes #1678

feat: improve compatibility with linkerd

---

pkg/specs/pods.go
pkg/specs/pods_test.go

Currently, if `AdditionalPodAffinity` and `AdditionalPodAntiAffinity` configs are not set, also `nodeAffinity` is not applied even if it is configured.
This patch fixes it.
Closes #1662

fix: ensure nodeAffinity is applied

---

cmd/kubectl-cnpg/main.go
docs/src/cnpg-plugin.md
internal/cmd/plugin/psql/cmd.go
internal/cmd/plugin/psql/doc.go
internal/cmd/plugin/psql/psql.go
internal/cmd/plugin/psql/psql_test.go
internal/cmd/plugin/psql/suite_test.go

With `kubectl cnpg psql` the user can start a `psql` connected to a
CloudNativePG cluster.
The user can select a role and additional parameters to be passed
to `psql`.
Closes: #1667

feat: kubectl-cnpg psql subcommand

---

tests/e2e/asserts_test.go
tests/e2e/cluster_microservice_test.go
tests/e2e/cluster_monolithic_test.go
tests/e2e/cluster_setup_test.go
tests/e2e/configuration_update_test.go
tests/e2e/eviction_test.go
tests/e2e/failover_test.go
tests/e2e/fastswitchover_test.go
tests/e2e/fencing_test.go
tests/e2e/logs_test.go
tests/e2e/pg_data_corruption_test.go
tests/e2e/pg_wal_volume_test.go
tests/e2e/replica_mode_cluster_test.go
tests/e2e/syncreplicas_test.go
tests/e2e/update_user_test.go
tests/e2e/upgrade_test.go
tests/utils/environment.go
tests/utils/postgres.go

Fixed a couple of misleading "1 second" timeouts which were sometimes failing to pass.
Bumped commandTimeouts from 5 to 10s to avoid the occasionally occurring "context deadline exceeded" errors.
Fixed SQL statements to make them idempotent when possible, otherwise changed them to be executed without retrying.

tests: relax E2E timeouts and make SQL statements idempotent

---

pkg/management/barman/capabilities/detect.go

The --name flag was added to Barman in version 3.3 but our implementation also requires the
barman-cloud-backup-show command which was not added until Barman version 3.4
Closes #1745

fix: our implementation of hasName requires Barman 3.4

---

api/v1/backup_webhook.go
api/v1/pooler_webhook.go
api/v1/scheduledbackup_webhook.go
config/crd/bases/postgresql.cnpg.io_clusters.yaml
config/crd/bases/postgresql.cnpg.io_poolers.yaml
internal/cmd/manager/controller/controller.go
internal/cmd/manager/instance/initdb/cmd.go
internal/cmd/manager/instance/join/cmd.go
internal/cmd/manager/instance/pgbasebackup/cmd.go
internal/cmd/manager/instance/restore/cmd.go
internal/cmd/manager/instance/run/cmd.go
internal/cmd/manager/instance/run/lifecycle/run.go
internal/cmd/plugin/fio/cmd.go
internal/cmd/plugin/fio/fio.go
internal/management/controller/instance_controller.go
internal/management/controller/instance_startup.go
internal/management/controller/slots/reconciler/replicationslot_test.go
internal/management/controller/slots/runner/runner_test.go
pkg/management/postgres/logicalimport/database.go
pkg/management/postgres/logicalimport/microservice.go
pkg/management/postgres/logicalimport/monolith.go
pkg/management/postgres/logicalimport/role.go
pkg/management/postgres/probes.go
pkg/management/postgres/restore.go
pkg/management/postgres/webserver/remote.go
pkg/reconciler/persistentvolumeclaim/reconciler_test.go
pkg/resources/retry.go
pkg/utils/fencing.go
tests/e2e/asserts_test.go

The new version of revive linter founds a lot of issues that are handled in this commit, some of them are:
* Unused variables
* Unneeded conditions before a return
* Redundant else in functions

chore: golangci-lint 1.52 comes with a new version of revive linter

---

.wordlist-en-custom.txt
controllers/cluster_controller.go
controllers/cluster_status.go
docs/mkdocs.yml
docs/src/declarative_hibernation.md
docs/src/samples/cluster-example.yaml
internal/cmd/plugin/status/status.go
pkg/reconciler/hibernation/doc.go
pkg/reconciler/hibernation/reconciler.go
pkg/reconciler/hibernation/reconciler_test.go
pkg/reconciler/hibernation/status.go
pkg/reconciler/hibernation/status_test.go
pkg/reconciler/hibernation/suite_test.go
tests/e2e/declarative_hibernation_test.go

This patch adds a declarative hibernation feature allowing the user to temporarily suspend the execution of a PostgreSQL cluster to save CPU time.
Clusters can be hibernated annotating them with
`cnpg.io/hibernation=on`. They will be rehydrated when the annotation will be removed or set to `off`.

feat: declarative hibernation

---

docs/src/cnpg-plugin.md
internal/cmd/plugin/report/logs.go
internal/cmd/plugin/report/operator_report.go
pkg/utils/logs/logs.go
pkg/utils/logs/logs_test.go
pkg/utils/logs/suite_test.go
tests/e2e/suite_test.go
tests/utils/cluster.go

Adding some improvement on how to get the previous logs of a pod including a small refactor on the stream logs functions to make easy to test
Closes #1801

chore: refactor stream log functions to easy handle options

---

.github/e2e-matrix-generator.py
.github/generate-test-artifacts.py
.github/workflows/continuous-delivery.yml

Adds proper detection of the Postgres KIND in the CI/CD - CIclops pipeline.
This makes flavor detection robust.

chore: make the postgres kind explicit in CI/CD

---

tests/e2e/fixtures/base/cluster-storage-class-with-rep-slots.yaml.template
tests/e2e/fixtures/fastfailover/cluster-fast-failover-with-repl-slots.yaml.template
tests/e2e/fixtures/fastswitchover/cluster-fast-switchover-with-repl-slots.yaml.template
tests/e2e/fixtures/replication_slot/cluster-pg-replication-slot-disable.yaml.template
tests/e2e/fixtures/switchover/cluster-switchover-with-rep-slots.yaml.template
tests/utils/import_db.go

Disabling logLevel `trace` on certain E2Es. It was previously added for debug purposes but it's not needed anymore.
Also adding a missing fallback for the `imageName` inside `ImportDatabasesMonolith()`

chore: disable logLevel trace on E2E tests using replication slots

---

api/v1/cluster_types.go
internal/management/controller/roles/contract.go
internal/management/controller/roles/contract_test.go
internal/management/controller/roles/postgres.go
internal/management/controller/roles/postgres_test.go
tests/e2e/managed_roles_test.go

This patch makes sure validuntil option of managed role changing
can reflect to the role in database.
Closes #1840

chore: reconciling for validUntil option changed

---

docs/src/samples/monitoring/cnpg-prometheusrule.yaml
docs/src/samples/monitoring/grafana-configmap.yaml

The example files shouldn't include helm metadata since they are not provided by helm.
Additionally, the PrometheusRule doesn't require the `grafana_dashboard` label as it isn't a dashboard.
I don't believe this requires backporting, but I'm unable to edit the labels.
Closes: #1981

fix: drop misleading metadata from examples

---

docs/src/samples/monitoring/cnpg-operator-podmonitor.yaml

This clones the PodMonitor definition from the docs into a quick place folks can pull down to test out the monitoring features provided by the operator container.

docs: provide sample for operator PodMonitor

---

internal/management/controller/instance_controller.go
pkg/management/postgres/utils/roles.go
pkg/management/postgres/utils/roles_test.go
pkg/management/postgres/utils/suite_test.go

The operator codebase now uses separate transactions to reconcile the credentials of multiple users.
Before this patch, the operator used a single transaction for all roles. A failure in the synchronization of a role led to a failure in the synchronization of every role, being the transaction rolled back as a whole.
The patch also includes a few fixes in the unit tests of related functions.
See: #1881

feat: use separate transactions to reconcile users' credentials

---

cmd/kubectl-cnpg/main.go

When the `completion` command was called while it was used inside the
`~/.basrc` file or a `~/.profile` this was useless since we were not able to output
the completion becase we were trying to create a Kubernetes client all the time,
which it's not the case during the load of a profile configuration, since this could
happen even before there's any Kubernetes cluster configured in place.
Closes #1932

Prevent creating Kubernetes client when calling completion command

---

Makefile
hack/e2e/run-e2e-local.sh
hack/e2e/run-e2e.sh
tests/e2e/upgrade_test.go

Invoking `make e2e-test-local` will run the E2E tests directly in the default Kubernetes cluster, assuming the operator is already deployed and configured.
It will run the tests using the default storage class (override it using E2E_DEFAULT_STORAGE_CLASS env variable) and the default operand in the current repository (override it using POSTGRES_IMG env variable).
Closes #2071

test: add e2e-test-local make target

---

controllers/cluster_upgrade.go
controllers/cluster_upgrade_test.go

The reason to delete a PostgreSQL Pod was registered into the status stanza of the CR and in an event.
This patch adds a log message which is helpful when diagnosing Clusters that have been deleted. It also fixes a minor issue: the operator was adding a event declaring a restart to "apply some PostgreSQL configuration change" even if the restart was triggered via the annotation.

feat: improve logging when deleting Pods

---

docs/src/bootstrap.md

Fix the example for the use of volume snapshot in the bootstrap section of the documentation.
Close #2139

docs: use the correct walStorage key

---

api/v1/cluster_webhook.go
api/v1/cluster_webhook_test.go
docs/src/index.md
docs/src/operator_capability_levels.md
docs/src/postgresql_conf.md
pkg/postgres/configuration.go
pkg/postgres/configuration_test.go

Closes #2042 
Add [pg_failover_slots](https://github.com/EnterpriseDB/pg_failover_slots),
which was recently released by EDB under the PostgreSQL license,
to the list of extensions managed by the operator.
When a user adds a pg_failover_slots.* option in the Postgres configuration
file, CloudNativePG automatically manage the `shared_preload_libraries` entry.

feat: Add `pg_failover_slots` to managed extensions

---

.github/workflows/backport.yml
.github/workflows/chatops.yml
.github/workflows/codeql-analysis.yml
.github/workflows/continuous-delivery.yml
.github/workflows/continuous-integration.yml
.github/workflows/kind-k8s-versions-check.yml
.github/workflows/latest-postgres-version-check.yml
.github/workflows/release-pr.yml
.github/workflows/release-publish.yml
.github/workflows/release-tag.yml
.github/workflows/require-labels.yml
.github/workflows/spellcheck.yml
tests/e2e/asserts_test.go
tests/e2e/operator_unavailable_test.go
tests/utils/cluster.go
tests/utils/operator.go

The version 20.04 of the ubuntu runners it's about to go end of life, and we should start using the latest version 22.04

chore: deprecating ubuntu-20.04 in favor of ubuntu-22.04 for GitHub actions

---

docs/src/monitoring.md

@mnencia
this it the PR following the [Slack Thread](https://app.slack.com/client/T03BCEDRZL1/C03D68KGG65/thread/C03D68KGG65-1684924144.695639)  
so that the "some_query" query can be copy/pasted into the example-monitoring configMap
br
Daniel

doc: fix some_query syntax

---

tests/utils/backup.go

we were creating backups in tests with `kubectl create`. In some cases
the backup could be created but not return success in time, and then
another `create` would be attempted and fail. This PR uses `apply`.

test: create backups with kubectl apply for safety

---

tests/e2e/asserts_test.go
tests/e2e/backup_restore_test.go
tests/e2e/cnpg_certificates_test.go
tests/e2e/configuration_update_test.go
tests/e2e/declarative_hibernation_test.go
tests/e2e/failover_test.go
tests/e2e/fastswitchover_test.go
tests/e2e/hibernation_test.go
tests/e2e/initdb_test.go
tests/e2e/logs_test.go
tests/e2e/managed_roles_test.go
tests/e2e/metrics_test.go
tests/e2e/pg_basebackup_test.go
tests/e2e/pg_data_corruption_test.go
tests/e2e/pg_wal_volume_test.go
tests/e2e/rolling_update_test.go
tests/e2e/syncreplicas_test.go
tests/e2e/update_user_test.go
tests/e2e/upgrade_test.go
tests/e2e/wal_restore_parallel_test.go
tests/utils/backup.go
tests/utils/cluster.go
tests/utils/pod.go
tests/utils/storage.go

Reuses the `GetCluster` function, introduces new functions to
centralize execution of commands on instance pods, and of
queries via local connection within the DB container

test: reuse core functions to fetch clusters and execute commands

---

api/v1/cluster_types.go
config/crd/bases/postgresql.cnpg.io_clusters.yaml
docs/src/api_reference.md
docs/src/samples/cluster-import-schema-only-basicauth.yaml
pkg/management/postgres/logicalimport/database.go

feat: add schemaOnly to the import section

---

controllers/cluster_controller.go
controllers/replicas.go
pkg/postgres/status.go

This commit addresses an issue where the failover process would continue even if the operator failed to extract status from the instances, potentially due to network connectivity issues. 
The operator now checks if the status has been successfully extracted from the instances before proceeding with the failover. If status extraction fails, the operator logs an error message, halts the current failover attempt, and reschedules another attempt after a delay.
Closes #2144

fix: halt the failover if status extraction has failed

---

.snyk

Since we were hitting so many false positive, this will exclude a long lists of files that must not be scanned.

chore: added Snyk exclude rules

---

docs/src/samples/monitoring/alerts.yaml
docs/src/samples/monitoring/cnpg-prometheusrule.yaml

The current setup only checked the `cnpg_pg_stat_archiver_last_failed_time`, meaning if any backup failed at least once in the complete database life, this alert stays forever. The current implementation is simple and just compare the previous value to the last_archived_time.

fix(alerts): refine LastFailedArchiveTime to not trigger if a new backup has been successful in the meantime

---

pkg/specs/services.go
pkg/specs/services_test.go

Addresses the issue where the -r service would be backed by the init and join pods.
Closes  #2335

fix: restrict read service to instance pods only

---

pkg/management/log/flags.go
tests/utils/environment.go

This commit addresses an issue where the log.SetLogger method was not being called, leading to an absence of displayed logs. The solution involves the creation and utilization of an internal logger constructor, which enhances reusability and ensures the proper function of the logging process.
Changes are made primarily in 'tests/utils/environment.go' and 'pkg/management/log/flags.go'. 
In 'tests/utils/environment.go', we configure and retrieve a logger instance and set this instance as the default logger. This setup manages the logger for the testing environment effectively.
In 'pkg/management/log/flags.go', new functions are introduced to create a new Flags instance and to manually set the log level, providing more flexibility and control over the logging process.
This change aims to …

chore: Implement internal log constructor to handle SetLogger error

---

.github/workflows/backport.yml

Previously the goal was to backport everything, and this works perfectly, but with renovate we create the PRs with the label `do not backport` which it's added because those PR will be replicated one per each release branch.
Now, we avoid adding the `backport-requested` label when the PR contains the `do not backport`

chore: do not add label `backport-requested` to `do not backport` PRs

---

internal/management/controller/slots/infrastructure/postgresmanager.go
internal/pgbouncer/management/controller/instance.go
internal/pgbouncer/management/controller/instance_test.go
internal/pgbouncer/management/controller/refresh.go
internal/pgbouncer/management/controller/refresh_test.go
internal/pgbouncer/management/controller/secrets_test.go
internal/pgbouncer/management/controller/suite_test.go
pkg/management/postgres/pool/pool.go

This commit introduces a new Pooler interface, which is designed to be a substitute for the ConnectionPooler direct usage. This change facilitates more effective and reliable unit testing of the codebase.
Additionally, this commit includes unit tests for various use cases of the ConnectionPooler within the pgbouncer management controller. These added tests enhance our ability to examine, debug, and ensure the overall reliability of the system.
Closes #2362

chore: introduce Pooler interface for improved unit testing

---

hack/setup-cluster.sh
tests/utils/version_test.go

This fixes an error in `setup-cluster.sh create -r` when used with
the latest version of Docker Desktop and contained beta feature enabled.
```
$ docker push 127.0.0.1:5000/fluentd-kubernetes-daemonset:local
4f3d1761e838: Waiting
458526b2e326: Waiting
c783e3bff97b: Waiting
missing content: content digest sha256:458526b2e326a53cbb5e2b6ba41401f0d21d06cbefe8581252c61c73ebc98783: not found
Note: You're trying to push a manifest list/index which references multiple platform specific manifests, but not all of them are available locally or available to the remote repository.
Make sure you have all the referenced content and try again.
```

fix: allow setup-cluster.sh to work with containerd

---

internal/management/controller/instance_controller.go

When getting the status of a pod and there's no sha256 in the status this could be nil, leading to a panic in the code while trying to check if there is a pending restart.
Closes #2389

fix: check for nil value in the pod status

---

docs/mkdocs.yml
docs/src/css/override.css

Override the readthedocs css theme for td and th, changing the white-space value from nowrap to normal. Long descriptions will be wrapped instead of forcing the user to horizontally scroll, improving the readability of the API Reference page.

doc: override table data css to wrap long sentences

---

.github/workflows/backport.yml

Previously the goal was to backport everything, and this works perfectly, but with renovate we create the PRs with the label do not backport which it's added because those PR will be replicated one per each release branch.
This is the further fix to avoid adding the backport-requested label when the PR is created by renovate

chore: do not add label backport-requested to PRs created by renovate

---

.devcontainer/devcontainer.json

This devcontainer configuration allows any user to instantly configure an environment capable of running all the tests (including E2E) and works well with [devpod](http://devpod.sh)

ci: devcontainer configuration

---

pkg/management/postgres/initdb.go
pkg/management/postgres/instance.go

In some system the storage may add a suid to the directory when the `fsGroup` in the security context it's enable,
making impossible to PostgreSQL to start since the permissions required are 0700 or 0750 but the directory 
may ended up with 2770
Closes #1354

fix: ensure PGDATA permissions after initdb and restore

---

.github/workflows/continuous-integration.yml

The CRD was not running because it was expecting only changes from `go-code-changed` in the `check-changes` job, now will also run if there's some changes in the `operator-changed` job.

fix: run the CRD check also when there's some changes in operator

---

api/v1/cluster_types.go
controllers/cluster_create.go
controllers/cluster_create_test.go

This patch ensures that we are able to reconcile the SA that we do not own, this is done by adding ownerMetadata only during the  creation of the SA.
Closes #2461

fix: add SA ownerMetadata only during creation

---

.github/workflows/continuous-delivery.yml
hack/e2e/volumesnapshotclass-ebs-csi.yaml
hack/e2e/volumesnapshotclass-pd-csi.yaml
tests/e2e/fixtures/volume_snapshot/cluster_volume_snapshot.yaml.template
tests/e2e/volume_snapshot_test.go
tests/utils/backup.go

This patch contains the configuration for e2e cloud env support 
for volumesnapshot. this patch include the changes for aks,eks and gke
And also a sample e2e test case for volumesnapshot backup
Closes: #2483

test: E2E cloud env configuration to support volumesnapshot

---

internal/cmd/plugin/snapshot/cmd.go

We were previously waiting for the snapshot to be not ready to use,
with this patch we check if there's an error inside the VolumeSnapshot
object and error out and let the user knows the error directly.

chore: Improve error output on snapshot command

---

pkg/management/pgbouncer/metricsserver/metricsserver_test.go
pkg/management/pgbouncer/metricsserver/pgbouncer_collector.go
pkg/management/pgbouncer/metricsserver/pools_test.go
pkg/management/pgbouncer/metricsserver/stats_test.go
pkg/management/pgbouncer/metricsserver/suite_test.go

This patch removes the use of the pool.ConnectionPool struct inside the pgbouncer/metricsserver package.
It substitutes the struct with the pool.Pooler interface and it also adds a basic unit test coverage to the package.
Partially Closes #2358

chore: add pool.Pooler interface to pgbouncer/metricsserver 

---

docs/src/bootstrap.md
docs/src/recovery.md

Move content from bootstrap.md regarding the `recovery` phase into recovery.md
in preparation for volume snapshot support.
Closes #2549

chore(docs): refactor `bootstrap.recovery` section

---

pkg/management/postgres/instance_test.go

I'm troubleshooting a situation on Tembo cloud. I'm manually breaking an instance on purpose to check how error reporting will work.
I ran `ALTER SYSTEM SET shared_preload_libraries = 'oopsies';`, then restarted my instance using the restartedAt annotation. Now, my instance is stuck in readiness 0/1 but liveness probe is passing, however I expected liveness probe to fail because pg_isready is not success. I found liveness probe is passing because the condition "MightBeUnavailable" is true, but I don't know why that is yet, currently I suspect it's related to triggering a restart.
I noticed this typo in the test while reviewing how "MightBeUnavailable" works.

Fix typo in test

---

ADOPTERS.md

Added a row to the adopters table for CNDI. CNDI is a framework for deploying self-hosted clusters with GitOps and IaC, where CNPG is one of the deployment Templates we provide.

(docs): Add CNDI to ADOPTERS.md

---

.golangci.yml
api/v1/cluster_webhook.go
pkg/management/barman/backupdelete.go
pkg/management/postgres/restore.go

After upgrading to golangci-lint 1.54.2 some new linter errors were detected. Also the new version of gosec linter 2.17.0 comes with an error that makes it to detect any variable longer than 24 as possible problem for G101, declared here https://github.com/securego/gosec/issues/1001 hence, that linter was disabled for now.

chore: fix linter errors in new version of golangci-lint

---

controllers/cluster_controller.go
controllers/cluster_upgrade.go
controllers/cluster_upgrade_test.go
pkg/specs/pods.go
pkg/utils/labels_annotations.go
pkg/utils/operations.go

- Add pod annotation with original PodSpec to detect drift.
- Use a standard structure for the functions checking if
rollout is needed.
- Fix logic that could allow a rollout with a Postgres image
from a different major version.

chore: detect PodSpec drift in pod rollout, and clarify rollout code

---

controllers/cluster_upgrade.go
pkg/specs/pods.go

In #2243 we encoded the podSpec annotation using the PB protocol. This commit changes the encoding to JSON.

fix: encode podSpec annotation in JSON

---

docs/src/replica_cluster.md
docs/src/samples.md
docs/src/samples/backup-with-volume-snapshot.yaml
docs/src/samples/cluster-example-replica-from-volume-snapshot.yaml
docs/src/samples/cluster-example-replica-streaming.yaml
docs/src/samples/cluster-example-with-volume-snapshot.yaml
tests/e2e/asserts_test.go
tests/e2e/fixtures/replica_mode_cluster/cluster-replica-from-backup.yaml.template
tests/e2e/fixtures/replica_mode_cluster/cluster-replica-from-snapshot.yaml.template
tests/e2e/fixtures/replica_mode_cluster/cluster-replica-src-with-backup.yaml.template
tests/e2e/metrics_test.go
tests/e2e/replica_mode_cluster_test.go
tests/e2e/volume_snapshot_test.go
tests/utils/backup.go
tests/utils/storage.go

This PR adds documentation on how to bootstrap a Replica Cluster from Volume Snapshots.
It also adds E2E tests to assert the bootstrap of Replica Clusters from either VolumeSnapshot or object store backup, and it slightly refactors the Replica Clusters E2Es
Closes #2388

chore: add documentation and E2E tests for Replica Clusters from VolumeSnapshot

---

tests/utils/time.go

This patch fix the failure about invalid time format in e2e test about PITR restore 
closes: #2665

test: pitr restore failed with invalid timestamp

---

api/v1/cluster_webhook.go
api/v1/cluster_webhook_test.go

This patch ensures we validate the `resources` stanza before creating the Cluster resources.
This will prevent the operator from indefinitely waiting for the jobs/pods to come online.
Closes #2661

chore: add webhook validation for the `resources` stanza

---

pkg/management/postgres/configuration.go
pkg/management/postgres/configuration_test.go

Only some of the values quoted meaning that that could lead to some issues with the pg_hba.conf parser in PostgreSQL. Also, there was an issue with secrets containing a new line at the end, now we add a `\` before the newline so PostgreSQL will read it only as one line.
Closes #2688

chore: properly quote the values inside LDAP fields for pg_hba.conf

---

controllers/cluster_upgrade.go
controllers/cluster_upgrade_test.go

The PodSpec drift checker was forcing instance rollout
whenever there was an operator upgrade.
This patch restores the logic allowing in-place instance manager
upgrades.

fix: instances always restarting on operator upgrade

---

tests/e2e/volume_snapshot_test.go
tests/utils/time.go

tests: add a timeout before gathering the targetTime in volumeSnapshot E2Es

---

config/manager/default-monitoring.yaml

The `pg_replication_slots` metric that is shipped by default with the operator is consistently failing on the replicas due to calls to WAL functions that are not available in the recovery phase. The metric is now run only on the primary.
Closes #2377
Closes #2552

fix(monitoring): run `pg_replication_slots` metric on primary only

---

docs/src/samples/cluster-example-monitoring.yaml

Fix the `pg_replication` metric to use the `pg_last_wal_receive_lsn()` and `pg_last_wal_replay_lsn()` functions to better estimate the lag of a replica, and avoid the increase of the lag on inactive systems.
Closes #1814

fix(monitoring): improve accuracy of replica lag

---

docs/src/recovery.md
pkg/management/postgres/restore.go

fix: evaluate `IsEmptyWalArchiveCheckEnabled` during restore

---

CONTRIBUTING.md

Added a link with a never expire option to not have this issue in the future
Closes #2801

chore: fix slack invitation link

---

.wordlist-en-custom.txt
api/v1/cluster_types.go
docs/src/labels_annotations.md
docs/src/troubleshooting.md
internal/cmd/manager/instance/pgbasebackup/cmd.go
internal/cmd/manager/instance/run/cmd.go
internal/management/controller/instance_controller.go
pkg/management/postgres/initdb.go
pkg/management/postgres/join.go
pkg/management/postgres/restore.go
pkg/system/compatibility/darwin.go
pkg/system/compatibility/unix.go
pkg/system/compatibility/windows.go
pkg/system/suite_test.go
pkg/system/system.go
pkg/system/system_test.go
pkg/utils/labels_annotations.go

Since it's useful to reduce the amount of memory used by a coredump when it's created we added this annotation to set the value for /proc/self/coredump_filter. The default value it's now set to 0x31 since it's look like the most used value.
The annotation can be set at cluster level and then will be passed in all the process that run any PostgreSQL command.
Closes #2696

chore: add coredumpFilter annotation

---

api/v1/cluster_types.go
config/crd/bases/postgresql.cnpg.io_clusters.yaml
docs/src/cloudnative-pg.v1.md
docs/src/instance_manager.md

BREAKING CHANGE: The default value of `switchoverDelay` has now been changed to 3600 seconds, equivalent of 1 hour. Previously, it was set to 40000000 seconds.
Closes #2845

feat!: change default value of `switchoverDelay` to `3600`

---

api/v1/cluster_types.go
config/crd/bases/postgresql.cnpg.io_clusters.yaml
docs/src/cloudnative-pg.v1.md
pkg/specs/pods.go
pkg/specs/pods_test.go

this patch provide the startupProbe support for postgres pod, 
the failureThreshold of startupProbe is calculated by startDelay / PeriodSeconds,
while PeriodSeconds is use default 10 seconds. startDelay by default is 3600
closes: #2843

feat: support startupProbe in instance pod

---

tests/e2e/asserts_test.go
tests/e2e/certificates_test.go

The connectivity test were failing due to a dependency of a previous test that should create the proper secret with the required certificate. Now, we create the certificate everytime in the test to keep the tests independent.

tests: ensure client certificate is always being created

---

pkg/specs/roles.go
pkg/specs/roles_test.go
pkg/stringset/stringset.go
pkg/stringset/stringset_test.go

Closes: #2861 
The empty string mentioned by #2861 comes from LADP secret name, refer to https://github.com/cloudnative-pg/cloudnative-pg/blob/main/api/v1/cluster_types.go#L2220-L2227.

fix: cleans up the resources lists in the generated Role

---

.github/workflows/continuous-integration.yml

The continuous-integration was only actually pushing images when a PR was labeled with "always push images".
But we should also produce the images whenever a new commit is pushed on main or a release branch.
This will ensure that the `ghcr.io/cloudnative-pg/cloudnative-pg-testing` main and release-* images are updated as soon as a new commit is pushed (up until now it was done only once per day via the continuos-delivery workflow)

chore: always push a new image after merging on main

---

internal/management/cache/cache.go
internal/management/controller/cache.go
pkg/management/postgres/webserver/local.go
pkg/management/postgres/webserver/metricserver/pg_collector.go
pkg/management/postgres/webserver/metricserver/wal.go

Closes: #2863 
I reviewed the instance manager log attached in #2860 and identified two significant points
```
goroutine 562 [running]:
reflect.mapiterinit(0x451652?, 0x1c0?, 0x1d96c40?)
/opt/hostedtoolcache/go/1.20.6/x64/src/runtime/map.go:1375 +0x19
reflect.(*MapIter).Next(0x1c7fc60?)
/opt/hostedtoolcache/go/1.20.6/x64/src/reflect/value.go:1919 +0x65
encoding/json.mapEncoder.encode({0xc00062d388?}, 0xc00048c280, {0x1c7fc60?, 0xc0004af678?, 0x800?}, {0xd?, 0x0?})
/opt/hostedtoolcache/go/1.20.6/x64/src/encoding/json/encode.go:797 +0x33e
encoding/json.structEncoder.encode({{{0xc000b0fb00?, 0x79c025?, 0xc00062d490?}, 0xc0006d9ad0?}}, 0xc00048c280, {0x1e35ae0?, 0xc0004af678?, 0xd?}, {0x0, 0x1})
/opt/hostedtoolcache/go/1.20.6/x64/src/encoding/json/encode.go:759 +0x1f4 …
```

fix: avoid write-read concurrency on cached cluster

---

pkg/management/postgres/metrics/collector.go

Ensure that `standard_conforming_strings` is set to `on` in every Prometheus connection transaction for metric collection. This is just in case users disable that globally.
Closes #2887

chore: enforce `standard_conforming_strings` in metric collection

---

docs/src/appendixes/object_stores.md

Updates the endpointURL for the Linode example in object_stores.md so that it does not include the bucket name and moves the bucket name into the S3 URL provided to destinationPath.
This is based on the recommendations in the current Linode documentation at:
https://www.linode.com/docs/products/storage/object-storage/guides/urls/#cluster-url-s3-endpoint
Closes #2629

fix: use correct endpointURL in Linode example (#2629)

---

docs/src/failure_modes.md

Warning against using `kubectl delete pod --grace-period=0`.
Closes #2910

docs: document how to simulate a failover

---

docs/src/samples/cluster-restore-snapshot-full.yaml
internal/cmd/manager/instance/restoresnapshot/cmd.go
pkg/fileutils/fileutils.go
pkg/fileutils/fileutils_test.go
pkg/management/postgres/configuration.go
pkg/management/postgres/restore.go

After the recovery process from a volume snapshot completes,
we need to cleanup the content of PGDATA, similarly to what
backup tools like Barman do. This is the list of files that we
remove from PGDATA:
- core.*
- pgsql_tmp*
- postgresql.auto.conf.tmp
- current_logfiles.tmp
- pg_internal.init
- postmaster.pid
- postmaster.opts
- recovery.conf
- recovery.signal
- standby.signal
- log/*
- pg_dynshmem/*
- pg_log/*
- pg_notify/*
- pg_replslot/*
- pg_serial/*
- pg_snapshots/*
- pg_stat_tmp/*
- pg_subtrans/*
Closes #2865

fix: ensure that restore snapshot cmd omits excluded files

---

config/manager/default-monitoring.yaml

Remove the `primary: true` requirement added in commit:23db603f.
Closes #1794

fix: make `pg_replication_slots` default metric run on replicas

---

pkg/fileutils/fileutils.go
pkg/fileutils/fileutils_test.go
pkg/management/postgres/restore.go

Properly log the cleanup phase of `PGDATA` in case of volume snapshot
recovery. Add a couple more unit tests.

chore: improve logging of PGDATA cleanup after recovery

---

controllers/backup_controller.go
internal/cmd/manager/controller/controller.go
pkg/utils/discovery.go
pkg/utils/discovery_test.go

This patch uses the discovery API to tell whether the VolumeSnapshot CRD is installed. If it isn't, the operator will continue working correctly but VolumeSnapshots backups will error out.
Closes #2931

fix: makes VolumeSnapshot CRD optional

---

api/v1/cluster_types.go
api/v1/cluster_webhook.go
api/v1/cluster_webhook_test.go
config/crd/bases/postgresql.cnpg.io_clusters.yaml
docs/src/cloudnative-pg.v1.md
docs/src/replication.md

IMPORTANT: the `.spec.replicationSlots.highAvailability.enabled` parameter is now by default set to `true`. This change was already anticipated in the upgrade instructions of CloudNativePG 1.20.
Closes #2673

feat: enable replications slots for HA by default

---

api/v1/backup_webhook.go
api/v1/backup_webhook_test.go
api/v1/scheduledbackup_webhook.go
api/v1/scheduledbackup_webhook_test.go
controllers/backup_controller.go
controllers/scheduledbackup_controller.go
pkg/utils/discovery.go

Improve UI of `VolumeSnapshot` support by preventing users from
creating `Backup` and `ScheduledBackup` resources with `volumeSnapshot`
as a `method` if the required CRDs are not installed in the underlying
Kubernetes cluster.

chore: forbid `volumeSnapshot` backups when CRDs are missing

---

docs/src/samples/monitoring/grafana-configmap.yaml
docs/src/samples/monitoring/grafana-dashboard.json

For the default Grafana dashboard,
- adds a new size gauge for WAL PVCs, and
- fixes the computation of the cache size
Closes #2836
Closes #2914
Signed-off-by: Daniel Chambre <smiyc@pm.me>

Grafana Dashboard: add WAL pvc usage

---

tests/e2e/asserts_test.go
tests/e2e/fixtures/metrics/custom-queries.yaml
tests/e2e/metrics_test.go

Since replication slot it's now a default the Metrics tests were looking for the metric `cnpg_pg_replication_slots_inactive` which it's not true anymore.
Closes #2968

fix: e2e tests looking for the wrong metric

---

pkg/specs/roles.go
pkg/specs/roles_test.go

This PR fixes a bug where backups were failing because of missing RBAC `resourceNames` on the `Role` object.
The bug only occurs when using other secrets for `region` and `sessionToken` than in `accessKeyId` or `secretAccessKey`.

fix(rbac): not adding `resourceNames` for `s3Credentials` `region` & `sessionToken`

---

controllers/cluster_create.go

This panic was happening when updating services created by really old versions of the operator, that was not generating any pre-defined labels and annotations.
Closes #2974

fix: panic in serviceReconciler

---

controllers/cluster_controller.go
controllers/cluster_restore.go
internal/cmd/plugin/psql/psql.go
pkg/reconciler/instance/metadata.go
pkg/reconciler/instance/metadata_test.go
pkg/reconciler/persistentvolumeclaim/metadata.go
pkg/reconciler/persistentvolumeclaim/reconciler_test.go
pkg/specs/pg_pods.go
pkg/specs/pods.go
pkg/specs/services.go
pkg/utils/labels_annotations.go
tests/e2e/asserts_test.go
tests/utils/cluster.go

This patch adds `cnpg.io/instanceRole` and deprecates the existing `role` label.
This new addition results from an ongoing effort to use only namespaced labels/annotations for uniformity and to avoid potential name clashes with other domains.
The deprecated `role` label will be removed in a future release.
Closes #2825

feat: add `cnpg.io/instanceRole` label

---

controllers/scheduledbackup_controller.go

At this moment, volume snapshot backups are cold backups, requiring PostgreSQL to be down.
If an immediate scheduled backup is created before the corresponding cluster, the latter won't be able to start because the primary node will be immediately fenced.
This patch makes the operator wait until the cluster is ready to take an immediate backup with volume snapshots.
Closes #2935

feat: defer immediate snapshot backup until cluster is Ready

---

tests/e2e/metrics_test.go

fixes the metrics test in the 1.20 and 1.19 branches, where replication
slots are not on by default

fix: metrics test should work with/without slots enabled

---

internal/cmd/plugin/status/status.go

If an instance is fenced, the `cnpg status` command now reports `Fenced` as `Replication role` instead of `Standby (starting up)`.
Closes #2994

fix(plugin): `status` to display `Fenced` status in `Replication role`

---

docs/src/samples/monitoring/grafana-configmap.yaml
docs/src/samples/monitoring/grafana-dashboard.json

Fixes #2965.
In addition this fixes metric duplication for `Last Archived WAL` and `Replication Lag`.
Before:
After:
Also I changed the UID of the dashboard to something non-random that makes your URL pretty:
P.S. It looks like the `ConfigMap` hasn't been updated even though the JSON file was. This PR fixes that and syncs up both files.

fix(grafana): manage unavailable backups situations

---

docs/src/postgresql_conf.md

Small note reminding users that all PostgreSQL parameters in the YAML definition need to be declared as strings.

docs: PostgreSQL parameters to be strings

---

docs/src/backup.md

```
kind: ScheduledBackup
....
spec:
...
schedule: 42 6 * * *
...
status:
lastCheckTime: "2023-08-17T18:06:42Z"
lastScheduleTime: "2023-08-17T18:06:42Z"
nextScheduleTime: "2023-08-17T19:06:42Z"
....
```
This seems like when I provide a five-term expression, we have the first term as seconds instead of minutes. In my opinion, it should either be interpreted like a kubernetes cron job, or have input validation error if there are only 5 terms.

fix(docs): Cron schedule expression in ScheduledBackup

---

config/manager/manager.yaml

Adding a default seccompProfile set to RuntimeDefault to the operator deployment.
Closes #2925

chore: add default seccompProfile to operator

---

controllers/backup_controller.go
controllers/backup_controller_test.go
pkg/reconciler/backup/volumesnapshot/reconciler.go
tests/e2e/fixtures/volume_snapshot/declarative-backup-on-primary.yaml.template
tests/e2e/volume_snapshot_test.go

This patch fixes an error condition when a cold snapshot backup is taken
on a single-instance cluster, or  if the primary was the `target` for
the snapshot.
In such case, the primary would be fenced, the backup would be blocked
on recognizing the target pod is not ready, and the primary would never
un-fence.
Closes #2948

fix: cold snapshot backup on primary leaves cluster stuck

---

api/v1/cluster_types.go
config/crd/bases/postgresql.cnpg.io_clusters.yaml
docs/src/cloudnative-pg.v1.md
docs/src/security.md

IMPORTANT: Change the default value of `.spec.enableSuperuserAccess` to `false`, in order improve the security by default posture of CloudNativePG by disabling superuser access via the network.
The rationale behind this is to foster a microservice approach where changes to PostgreSQL are performed in a declarative way through the `spec` of the `Cluster` resource, while providing developers with full powers inside the database through the database owner user. At the same time, give the possibility to users to enable it by explicitly setting `.spec.enableSuperuserAccess: true`.
Closes #2899

feat: disable `postgres` super user access by default

---

.github/workflows/continuous-delivery.yml
.github/workflows/continuous-integration.yml
tests/e2e/initdb_test.go

Fixes the use of CIclops in the continuous delivery pipeline.
CIclops has been detecting systematic failures in `main`, but
was unable to send an alert via slackops

fix: ciclops unable to slack for alerts

---

api/v1/pooler_types.go

An "ro" PoolerType creates a pooler with the "ro" service as it's backend, which means it'll provide a connection pool over all replicas, excluding the primary.

Fix PoolerTypeRO comment

---

.wordlist-en-custom.txt
api/v1/cluster_types.go
config/crd/bases/postgresql.cnpg.io_clusters.yaml
docs/src/cloudnative-pg.v1.md
docs/src/fencing.md
docs/src/instance_manager.md
internal/management/controller/instance_controller.go
pkg/management/postgres/instance.go
tests/e2e/fixtures/fastfailover/cluster-fast-failover-with-repl-slots.yaml.template
tests/e2e/fixtures/fastfailover/cluster-fast-failover.yaml.template
tests/e2e/fixtures/fastfailover/cluster-syncreplicas-fast-failover.yaml.template

Rename the newly introduced `smartStopDelay` parameter (never released)
into a clearer one called `smartShutdownTimeout`, which exactly describes
the intention of that option: control for how long we wait for PostgreSQL
to execute a graceful shutdown when requested, before trying a fast one
(during shutdown or fencing, for example).
Closes #3027

chore: rename `smartStopDelay` to `smartShutdownTimeout`

---

.devcontainer/devcontainer.json

Improve the devcontainer environment by adding bash-git-prompt
and using bullseye instead of bookworm, which doesn't have 
the right support for Python and doesn't work on ARM64.

ci: improve devcontainer environment

---

Makefile

GoReleaser requires tags to create a release, which is not necessary true when running on a forked repo, this will fix that by checking the VERSION variable, which if is empty, means that there's not tag's on the current repo, in that case, we add the option `--snapshot` to the goreleaser command when doing `make docker-build`
Closes #2179

ci: use snapshot mode when no tags exist

---

.wordlist-en-custom.txt
docs/src/installation_upgrade.md
docs/src/instance_manager.md

List all the significant changes applied to the default values in 1.21.0, 1.20.3, and 1.19.5, while providing instructions on how to keep the existing behavior on new clusters too.
Closes #2988

docs: upgrade instructions to 1.21.0, 1.20.3 and 1.19.5

---

docs/src/backup.md
docs/src/backup_volumesnapshot.md
docs/src/kubectl-plugin.md
docs/src/recovery.md
internal/cmd/plugin/snapshot/cmd.go

Update the backup, recover, and plugin documents to reflect
the state of support for volume snapshots.
Closes #3031

doc: update the information on volume snapshots

---

.github/workflows/continuous-integration.yml

should fix this issue in the CI/CD: https://github.com/cloudnative-pg/cloudnative-pg/commit/6b41d6cedda5f79580fe948fee46996cf90ae442/checks

ci: raise goreleaser cnpg plugin build timeout

---

api/v1/cluster_types.go
config/crd/bases/postgresql.cnpg.io_clusters.yaml

Remove the default value for `.spec.bootstrap.import.schemaOnly`
to fix the UI in the OLM Cluster creation interface.
Closes #3106

fix: `schemaOnly` import doesn't need a default value

---

internal/cmd/manager/instance/run/lifecycle/lifecycle.go
internal/cmd/manager/instance/run/lifecycle/run.go
internal/management/controller/instance_controller.go
internal/management/controller/instance_startup.go
pkg/management/postgres/instance.go
pkg/management/postgres/instance_test.go
pkg/management/postgres/promote.go

chore: use `contextLogger` in the instance when possible

---

docs/src/backup.md
docs/src/storage.md

Provide a link to the official Kubernetes documentation that lists the supported Container Storage Interface (CSI) drivers - showing which ones provide volume snapshotting capabilities.
Closes #3084

docs: provide a link to the list of CSI drivers

---

pkg/management/postgres/webserver/remote.go

This patch adjusts several log messages for the HTTP endpoints.
In case of HTTP probe failures, we avoid cluttering the logs by printing an info message, given that this information can still be obtained from pod status.
In case of unmarshal errors, we instead raise the severity from info to warning.
Closes #2958

chore: adjust log levels of the instance endpoints

---

.github/workflows/continuous-integration.yml
Makefile

Adding this new check from https://go.dev/security/vuln/ allows to detect any vulnerability locally using the Go vulnerability database which is faster and will work locally integrated inside the checks list.
Closes #3126

chore: add a new check `run-govulncheck`

---

tests/utils/cluster.go

`GetClusterPrimary` is not deprecated, the `cnpg.io/cluster` label is.

docs: GetClusterPrimary deprecation

---

pkg/management/postgres/webserver/metricserver/pg_collector.go
pkg/utils/conditions.go

We should use `(*regexp.Regexp).MatchString` instead of `(*regexp.Regexp).Match([]byte(...))` when matching string to avoid unnecessary `[]byte` conversions and reduce allocations. Although the improvement is not significant, it is a one-line change for free performance.
Example benchmark:
```go
func BenchmarkMatch(b *testing.B) {
for i := 0; i < b.N; i++ {
if match := conditionReasonRegexp.Match([]byte("NewReplicaSetAvailable")); !match {
b.Fail()
}
}
}
func BenchmarkMatchString(b *testing.B) {
for i := 0; i < b.N; i++ {
if match := conditionReasonRegexp.MatchString("NewReplicaSetAvailable"); !match {
b.Fail()
}
}
}
```
Result:
```
goos: linux
goarch: amd64
pkg: github.com/cloudnative-pg/cloudnative-pg/pkg/utils cpu: AMD Ryzen 7 PRO 4750U with Radeon Graphics
BenchmarkMatch-16 …
```

perf: avoid allocations with `(*regexp.Regexp).MatchString`

---

pkg/reconciler/backup/volumesnapshot/reconciler.go
pkg/reconciler/backup/volumesnapshot/reconciler_test.go
tests/utils/storage.go

This patch ensures we only add meaningful labels to the created `VolumeSnapshots` resources.
The non-meaningful values are moved inside the annotations map.
Closes #3148

fix: avoid cluttering `VolumeSnapshots` with labels

---

.github/workflows/release-publish.yml

Given that the first cnpg release on [OperatorHub.io](https://operatorhub.io/operator/cloudnative-pg) has been done, we can now enable the automatic process to create a PR to update an existing operator.
On release, a new Pull Request will be created on the [https://github.com/cloudnative-pg/community-operators](https://github.com/cloudnative-pg/cloudnative-pg/issues/cloudnative-pg/community-operators) fork, which will be relayed to the source k8s-operatorhub/community-operators repository after being reviewed.
Closes #3116

chore: enable automatic release process to OperatorHub.io

---

Makefile

Using the LOCALBIN path of the code helps to keep encapsulated the binaries
and easy to cleanup with a new version every time.
Closes #3158

fix: move the install path of opm and operator-sdk to localbin

---

.github/workflows/continuous-integration.yml

The GITHUB_TOKEN has restricted permissions if the pull_request has been opened 
from a forked repository, so we avoid pushing to the container registry if that's the case.
See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
Closes #3154

ci: avoid pushing container images if we are running from an external PR

---

api/v1/backup_types.go
controllers/backup_controller.go
pkg/reconciler/backup/volumesnapshot/reconciler.go
pkg/reconciler/backup/volumesnapshot/reconciler_test.go
pkg/reconciler/backup/volumesnapshot/resources.go
pkg/reconciler/backup/volumesnapshot/resources_test.go

Since VolumeSnapshots are consistent and the existence of a VolumeSnapshotContent object is enough to declare the snapshot cut, we're lifting fencing directly as soon as a VolumeSnapshotContent have been provisioned.
Closes: #3200

fix: reduce fencing window for snapshot backups

---

internal/cmd/manager/walarchive/cmd.go

To avoid the replicas to relentlessly follow the new timeline created by a promotion that didn't complete corrently, we now delay the WAL archiving process on a former standby until the switchover is completed.
Closes: #3147
Related: #2766

fix: defer WAL archiving until the switchover have been completed

---

tests/utils/psql_client.go

As the psql pod might be deleted by cases of Drain Node, we need to make use of the `StatefulSet` or `Deployment` to keep the pod running. To avoid the code that references the psql pod breaking due to a random name created by Deployment, we choose to use the `StatefulSet`
Closes #3197

fix: Keep the psql-client pod running

---

docs/src/kubectl-plugin.md
internal/cmd/plugin/backup/cmd.go
internal/cmd/plugin/backup/doc.go

This patch introduces three new optional flags to the `backup` command of the `cnpg` plugin that control the online backup taken with the `volumeSnapshot` method. Those flags will be passed to the generated `Backup` resource.
Closes #3168

feat(plugin): command options for volume snapshots hot/cold backups

---

pkg/management/postgres/configuration.go

In the [pull request](https://github.com/cloudnative-pg/cloudnative-pg/pull/2812), we migrated settings from `postgresql.auto.conf` to `override.conf`. During this migration, we overlooked the `recovery_target_timeline` setting. As a result, the reloaded configuration file does not include `recovery_target_timeline`, leading to a PostgreSQL restart.
closes: #3221

fix: Migrate recovery_target_timeline to prevent restarting

---

Makefile

Adding this allow users using OLM bundle from OperatorHub.io to use the bundle manually in their OpenShift cluster allowing a secure upgrade if needed.
Closes #3191

chore: add OpenShift annotations to the bundle metadata

---

api/v1/cluster_webhook.go
controllers/cluster_controller.go
controllers/cluster_create.go
docs/src/security.md
pkg/reconciler/persistentvolumeclaim/validation.go
pkg/reconciler/persistentvolumeclaim/validation_test.go

Before recovering from a set of VolumeSnapshots, the operator will validate if the labels are there and are coherent with the requested recovery settings.
Closes: #2980

feat: volume snapshot validation

---

contribute/e2e_testing_environment/README.md
hack/setup-cluster.sh

This patch enhances the `setup-cluster.sh` script to transparently export the
`DOCKER_DEFAULT_PLATFORM=linux/arm64` on arm64 architectures.
This way the docker engine can properly retrieve the correct node images architecture.
Closes: #3240

chores: add document for arm64 architecure in development guide

---

pkg/management/postgres/restore.go

Up to now, the recovery job was discarding WAL files by setting `archive_command` to `cd .` (that is success). We now set it to `false`, so that we defer the decision about archiving a WAL file to when the instance is actually started as a regular pod.
Closes #3259

fix: defer WAL archiving during a recovery job

---

pkg/reconciler/backup/volumesnapshot/reconciler.go
pkg/reconciler/backup/volumesnapshot/resources.go
pkg/reconciler/backup/volumesnapshot/resources_test.go

fix: retry when external-snapshotter controller failed on a conflict

---

pkg/management/postgres/pool/pool.go

When taking an hot snapshot backup, we require an exclusive connection for the PostgreSQL Physical Backup API.
In that case, the number of available connections for the other instance manager runnables will be reduced to one. To avoid those other runnables to be stuck, we allow one more PostgreSQL connection.
Closes: #3275

chore: allow one more connection to PostgreSQL from the instance manager

---

controllers/cluster_upgrade.go
controllers/cluster_upgrade_test.go

Fixes a bug where the PodSpec annotation was stored as Protobuf, but after
upgrade, was expected as JSON. This fix skips the PodSpec rollout check in
this case, defaulting to the pre-PodSpec rollout checkers.
Closes: #3273

fix: skip podSpec rollout checker if pod annotation is invalid

---

docs/src/declarative_role_management.md
tests/e2e/fixtures/managed_roles/cluster-managed-roles.yaml.template
tests/e2e/managed_roles_test.go

We didn't like to store the password in plain text and tried to specify the password hash. It worked. So here is some documentation and an e2e test :)

chore: document usage of hashed passwords

---

hack/release.sh

During the release procedure, we update the link to install the latest snapshot of the operator together with the other. That link should always point to the latest snapshot from the main branch.

ci: do not update the install latest code link

---

.github/workflows/continuous-integration.yml
.wokeignore

chore: scan operator image using Dockle and Snyk

---

controllers/backup_controller.go
pkg/management/postgres/webserver/backup_client.go
pkg/management/postgres/webserver/backup_connection.go
pkg/management/postgres/webserver/remote.go
pkg/management/postgres/webserver/webserver.go
pkg/reconciler/backup/volumesnapshot/offline.go
pkg/reconciler/backup/volumesnapshot/online.go
pkg/reconciler/backup/volumesnapshot/reconciler.go
pkg/reconciler/backup/volumesnapshot/reconciler_test.go

In the old code for the status endpoint, we evaluated the body errors as an error response code. This needed to be corrected, given that this would lead the old code to an infinite stuck-on error response when the held backup connection contained an error.
With the new implementation, the caller determines if the returned body error is relevant to the backup that is trying to run.
The patch also ensures that requests for outdated backups aren't processed.

fix: correctly evaluate the request and response for the backup mode

---

docs/src/declarative_role_management.md
internal/cmd/plugin/status/status.go

This PR aims to improve the user experience by integrating the `cnpg status` command with the RoleManager status data.

chore: add `RoleManager` section to `cnpg status`

---

docs/src/backup.md

In the documentation, we were using the unicode
U+10102	AEGEAN CHECK MARK
to denote an "x mark" in a feature table. It is not rendered
in Windows (not included in the Segoe UI Symbols font).
This PR uses instead the more standard
U+2717	BALLOT X (cross)
which has wider support
Closes #3361

docs: fix x-mark inaccessibility

---

controllers/cluster_create.go
controllers/cluster_create_test.go
pkg/specs/poddisruptionbudget.go

This patch ensures that we reconcile `pdb` metadata changes.
Without the proposed changes, the code doesn't for metadata changes and injects the cluster `SetInheritedDataAndOwnership` only during `pdb` creation.

fix: reconcile `pdb` metadata

---

controllers/pooler_resources_test.go
controllers/pooler_update.go
controllers/pooler_update_test.go
pkg/specs/pgbouncer/services.go
pkg/specs/pgbouncer/services_test.go

This patch fixes two issues that we currently have with the Pooler service.
a) we never reconcile the service once is created
b) we don't add the proper labels to the created service

fix: reconcile `Pooler` service and add labels.

---

pkg/specs/pgbouncer/deployments.go
pkg/specs/pgbouncer/deployments_test.go

This patch ensures that we add the proper labels to the deployment. In a previous patch we ensured that the labels were present on the pods but not on the actual deployment.

fix: add proper labels to the `Pooler` deployment

---

controllers/pooler_controller.go
controllers/pooler_controller_test.go

In the current `main` code, we only watch for secrets that match the statement `pooler.GetAuthQuerySecretName() == secret.Name`, omitting the other useful secrets from being watched. This patch fixes this behavior by ensuring that the controller watches any secret owned by a `Pooler`.

fix: watch the secrets owned by a given `Pooler`

---

.github/workflows/backport.yml
.github/workflows/continuous-delivery.yml
hack/e2e/run-e2e.sh

This patch contains the fix for the workflow failure issue, one is missing docker registry 
env variable in e2e test, the other is missing pull-request read permission for github_token

ci: fix workflow failed issue

---

internal/management/controller/roles/postgres_test.go
pkg/management/postgres/logicalimport/database_test.go
pkg/management/postgres/probes_test.go

In version 1.5.1, the go-sqlmock module became stricter about missing
parameters in query expectations. This patch adds a few missing
parameters to our unit tests.

test: fix go-sqlmock v1.5.1 compatibility

---

.github/workflows/continuous-delivery.yml
.github/workflows/continuous-integration.yml

This patch move the snyk scan to cd workflow, as this scan require
secrets in cloudnative-pg repository
Closes: #3451

ci: move image scan to cd workflow

---

contribute/development_environment/README.md

Update the required version of Go from 1.17 to 1.21 and kind from v0.11.x to v0.20.x 
Closes: #3526

doc: update Go and Kind version in contributing guide

---

api/v1/pooler_types.go
api/v1/zz_generated.deepcopy.go
controllers/pooler_update_test.go
controllers/suite_test.go
pkg/specs/pgbouncer/deployments.go
pkg/specs/pgbouncer/deployments_test.go
tests/e2e/fixtures/upgrade/pgbouncer.yaml
tests/e2e/upgrade_test.go

This patch ensures that the pooler can be scaled to zero.
Closes #3502

fix: make pooler instances a pointer

---

.wordlist-en-custom.txt
api/v1/cluster_types.go
config/crd/bases/postgresql.cnpg.io_clusters.yaml
docs/src/cloudnative-pg.v1.md
docs/src/installation_upgrade.md
docs/src/postgresql_conf.md
internal/management/controller/instance_controller.go
pkg/management/postgres/instance.go
pkg/management/postgres/instance_test.go

Introduce the `.spec.postgresql.enableAlterSystem` to enable/disable the usage of the `ALTER SYSTEM` command for a PostgreSQL instance. Internally, the operator disables writes on the `$PGDATA/postgresql.auto.conf` file when `.spec.postgresql.enableAlterSystem` is set to `false`.
For back compatibility, the default is `true`.
Closes: #2725

feat: allow users to disable ALTER SYSTEM

---

api/v1/cluster_types.go
config/crd/bases/postgresql.cnpg.io_clusters.yaml
docs/src/cloudnative-pg.v1.md
docs/src/installation_upgrade.md

this patch make option `.spec.postgresql.enableAlterSystem` disable by default 
since 1.22.0 release. the option is introduced in through this [patch](https://github.com/cloudnative-pg/cloudnative-pg/pull/3535).
Closes #3544

feat: disable ALTER SYSTEM by default

---

controllers/replicas.go

**Problem** 
Current implementation does not take into consideration whether a target primary for a switchover has an active wal_receiver session.  This leads to potential situations where a pod can be selected as target primary even if it is in the process of running wal-restore to catch up.
**Context** 
We encountered this issue on a high-write postgres instance with two replicas. We were forced to bounce one replicas and after the join-job completed it began trying to catch up using wal-restore. The pod was ready and got targeted as primary due to k8s node maintenance trying to move the primary off an unschedulable node. 
Unluckily the pod running wal-restore was selected to be primary instead of the other replica which was up-to-date, leading to hours of write-downtime as wal-restore …

Verify candidate has active wal_receiver before targeting as primary

---

.github/workflows/continuous-delivery.yml

This is needed to support upload-artifact and download-artifact v4.

fix(e2e): avoid uploading multiple artifacts with same name

---

docs/src/recovery.md

Some examples in the documentation page `recovery.md` have the wrong indentation:
The `bootstrap` block is at the same indentation level as the spec block, when it should belong to the `spec` block according to the API documentation: https://cloudnative-pg.io/documentation/1.21/cloudnative-pg.v1/#postgresql-cnpg-io-v1-ClusterSpec

fix(doc): indentation of example in `recovery.md`

---

.github/renovate.json5
.github/workflows/public-cloud-k8s-versions-check.yml

We were updating even alpha version of KinD which is not desired, from now on,
we exclude any kindest/node image that contains the "alpha" string on it

fix(ci): do not consider alpha version of KinD

---

pkg/reconciler/persistentvolumeclaim/storagesource.go
pkg/reconciler/persistentvolumeclaim/storagesource_test.go

This patch prevents CNPG from using backups that are older than the created Cluster when bootstrapping a new replica.
Closes: #3563

fix: avoid considering old snapshots when creating a replica

---

docs/src/samples/monitoring/grafana-configmap.yaml
docs/src/samples/monitoring/grafana-dashboard.json

Adds a new dedicated gauge series for tablespaces volumes. See image below.
The PromQL query buried within the Grafana dashboard JSON:
``` yaml
max(
sum by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace="$namespace", persistentvolumeclaim=~"(${instances})-tbs.*"}) 
/
sum by (namespace,persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace="$namespace", persistentvolumeclaim=~"(${instances})-tbs.*"}) 
*
on(namespace, persistentvolumeclaim) group_left(volume)
kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~"$instances"}
) by (volume)
```
The cluster manifest used to generate the image (see below), as applied in Part 4 of the Quickstart guide:
``` yaml
kubectl apply -f - <<EOF
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata: …
```

feat: add gauges for the tablespace volumes in grafana

---

pkg/management/postgres/join.go

We explicitly set a high-enough wal_sender_timeout for join-related pg_basebackup executions. A short timeout could not be enough in case the instance is slow to send data, like when the I/O is overloaded.
Fixes #3337

fix: set wal_sender_timeout to 5min when joining through pg_basebackup

---

docs/src/samples/monitoring/grafana-configmap.yaml
docs/src/samples/monitoring/grafana-dashboard.json

Hi there!
This panel in the example dashboard was reporting the wrong value because there was a negative that wasn't being negated. Here's the before image:
And here's after:
Comparison:
Let me know if there's anything else you want me to test!

Fix example Grafana dashboard's "Last archived WAL" panel

---

pkg/reconciler/backup/volumesnapshot/online.go

The body error check within the `finalize` method of the volume snapshot backup has been removed. This check was redundant and unnecessary since we are already checking for errors inside the `EnsureDataIsPresent` function, and it would never be triggered.

chore: remove useless code inside snapshot `finalize`

---

tests/e2e/fixtures/upgrade/backup1.yaml
tests/e2e/fixtures/upgrade/scheduled-backup.yaml

This patch enforce the e2e test case to backup from primary, to avoid the backup is waiting 
for checkpoint to start in standby

test: enforce backup from primary in upgrade e2e

---

controllers/cluster_upgrade.go
controllers/cluster_upgrade_test.go

This patch prevents the rollout of the pod in case the current and expected `.spec.projectedVolumeTemplate.sources` use different semantics to describe a  volume source not being present.
Previously, we required a strict equivalence between the current and expected values of `.spec.projectedVolumeTemplate.sources`, which resulted in the operator initiating rollouts even when comparing zero and nil values.
Closes: #3623

fix: correctly compare zero and nil `.spec.projectedVolumeTemplate.sources`

---

pkg/postgres/configuration.go

This patch resolves a bug in the code execution caused by incorrect quoting introduced with PR #3534.

fix: properly quote comment lines

---

api/v1/pooler_types.go
api/v1/pooler_webhook.go
controllers/cluster_status.go

Closes #2479
Removes the noisy log, only logging on the Pooler creation or update (once) if needed and returning warning to user.
```
cnpg-controller-manager-86cf7ff964-m5hp9 manager {"level":"info","ts":"2023-12-16T12:32:27Z","logger":"pooler-resource","msg":"Pooler not automatically configured, manual configuration required","version":"v1","name":"pooler-example-rw","namespace":"default","cluster":"cluster-example"}
```

feat(pooler): warn and log manual integration required

---

pkg/management/postgres/configuration.go
pkg/management/postgres/ident.go

This patch eliminates the repetition of code that was previously used to identify the current Postgres user.
Closes #3679

refactor: centralize the get current Postgres user logic

---

.wordlist-en-custom.txt
api/v1/cluster_types.go
api/v1/cluster_webhook.go
api/v1/cluster_webhook_test.go
api/v1/zz_generated.deepcopy.go
config/crd/bases/postgresql.cnpg.io_clusters.yaml
docs/src/cloudnative-pg.v1.md
docs/src/cluster_conf.md
pkg/specs/volumes.go
pkg/specs/volumes_test.go

Allow the user to optionally set the ephemeralStorage option in the cluster spec.
Closes #3677
Refs:
- https://github.com/cloudnative-pg/cloudnative-pg/issues/3677
- https://github.com/cloudnative-pg/cloudnative-pg/issues/317

feat: add ephemeralVolumeSource option to cluster spec.

---

pkg/management/external/internal/pgpass/conninfo.go
pkg/management/external/internal/pgpass/conninfo_test.go

Escape `:` and `\` characters according to pgpass file escaping rules.
Ref: https://www.postgresql.org/docs/current/libpq-pgpass.html
Fixes #3712

fix: escape reserved characters in pgpass fields (resolves #3712)

---

.github/workflows/continuous-delivery.yml

We are limiting to local executors when running Scheduled E2Es, while instead we should be running the tests also on each supported cloud provider.

ci: re-establish cloud providers on scheduled E2Es

---

internal/management/controller/instance_controller.go
internal/management/controller/instance_startup.go
pkg/management/postgres/instance.go

pg_rewind needs to be able to write to all the files in the PostgreSQL data
directory. For this reason, we always set `postgresql.auto.conf` mode to 600
before running it.
After the PostgreSQL data directory is ready to be used, we revert the
permission to be coherent with what the user specified in the `enableAlterSystem`
configuration parameter.
Closes: #3698

fix: enforce postgres.auto.conf to rw before run rewind

---

internal/management/controller/slots/reconciler/replicationslot.go
internal/management/controller/slots/reconciler/replicationslot_test.go

This patch enfore when a HA replication slot is not the expected one, cnpg delete the 
replicationslot only when it changes to inacive status. 
Closes: #3739

fix: skip deleting ha replicationslot when it is active

---

docs/src/database_import.md
docs/src/samples/cluster-import-schema-only-basicauth.yaml
docs/src/samples/cluster-import-snapshot-basicauth.yaml
docs/src/samples/cluster-import-snapshot-tls.yaml
pkg/configfile/configfile.go
pkg/fileutils/fileutils.go
pkg/management/postgres/configuration.go
pkg/management/postgres/initdb.go
pkg/management/postgres/restore.go

When using the import facility of the initdb bootstrap method in a job, optimize the PostgreSQL instance for the sole duration of the job, by setting the following GUCs:
- `archive_mode` to `off`
- `fsync` to `off`
- `full_page_writes` to `off`
- `max_wal_senders` to `0`
- `wal_level` to `minimal`
Then, restore the configuration and invoke `initdb --sync-only` before the end of the import job.
This avoids unnecessary and systematic piling of WAL files during any import job.
Closes #3741

fix: disable WAL archiving during import bootstrap

---

docs/src/release_notes/v1.21.md
docs/src/release_notes/v1.22.md
pkg/management/postgres/configuration.go
pkg/management/postgres/instance_replica.go
pkg/management/postgres/restore.go

Postgres always parses `postgresql.auto.conf` as the last configuration file. This file contains settings dynamically changed through the `ALTER SYSTEM` SQL command.
When CloudNativePG introduced the `enableAlterSystem` parameter, the content from `postgresql.auto.conf` was migrated into `override.conf` at startup.
This patch improves the check by making it idempotent and by running it in the reconciler, ensuring that no option contained in `override.conf` is in `postgresql.auto.conf`.
Closes #3588

fix: prune `override.conf` settings from `postgresql.auto.conf`

---

.github/workflows/continuous-delivery.yml

Previously we were using only the run number from the GitHub action which was unique, meaning that all the cluster were being created with the same hostname, now, we add the OCP version to the domain to avoid these kind of issues
Closes #3799

fix: add the OCP version to the cluster name when creating for testing

---

.github/workflows/continuous-delivery.yml
.github/workflows/continuous-integration.yml
.github/workflows/release-publish.yml

Until now, we were supposing that we were using Dockerfile by default and just specify when we wanted to use Dockerfile-ubi8, now, we're explicitly on which file we use, this is for in the future, avoid making mistakes of which file we're using to build the container images.
And since we're using more than one Dockerfile to build image, we also added a new stop to build that image and run the Dockle scan process on that one.
Closes #3811

chore: make clear which Dockerfile use every build process

---

.github/renovate.json5

We were missing operator-sdk in renovate so we were not updating the version to the latest one.
Closes #3866

fix: add operator-sdk to the renovate updates

---

Makefile

Downgrade operator permissions in OLM deployments from Cluster level (`ClusterRole` and `ClusterRoleBinding`) to the namespace level (`Role` and `RoleBinding`).
Closes #3854

fix(olm): use `Role` instead of `ClusterRole` for operator permissions

---

controllers/replicas.go

For an INFO level log we were logging the full pod object with all the 
information inside resulting in a big log that turns out to be totally 
useless since the main message was lost.
Closes #3856

fix: avoid logging the entire primary pod object

---

tests/e2e/backup_restore_test.go
tests/e2e/tablespaces_test.go

With this patch, we make sure that the WAL files are all archived after we take
the backup; this will reduce the amount of time required by the restore process
when the backup is taken from standby, as it will not wait for the WAL files to
be archived on the primary.
The time is reduced from ~9m to ~4m
This patch is a quick fix to improve the time of our tests, but we need to
refactor it in a broader initiative about backup testing E2E test improvements.
Closes #3910

fix: reduce the time required for the tablespaces test

---

pkg/management/barman/capabilities/detect.go
pkg/management/barman/capabilities/detect_test.go
pkg/management/barman/capabilities/suite_test.go

This patch ensures that we correctly detect barman google capability. 
It also adds unit tests coverage for barman capabilities discovery.
Closes #3929

fix: correctly populate barman google capabilities

---

Makefile
tests/e2e/upgrade_test.go
tests/utils/upgrade.go

While doing the upgrade process if we don't add the `--force-conflicts` along side with the `--server-side` we can't apply the new manifest meaning that the upgrade test fails. Now we added this `--force-conflicts` option that we already documented in the upgrade process.
More information here https://kubernetes.io/docs/reference/using-api/server-side-apply/#conflicts
Closes #4000

fix: add --force-conflicts options to kubectl apply

---

api/v1/cluster_types.go
api/v1/cluster_types_test.go
controllers/cluster_controller.go
controllers/cluster_status.go
controllers/cluster_upgrade.go
docs/src/index.md
docs/src/installation_upgrade.md
pkg/executablehash/executablehash.go
pkg/management/upgrade/suite_test.go
pkg/management/upgrade/upgrade.go
pkg/management/upgrade/upgrade_test.go
pkg/utils/discovery.go
pkg/utils/discovery_test.go
pkg/utils/reconciliation.go

From the catalog of all the available architectures contained in the running operator image, retrieve the matching architecture's binary during in-place updates, enabling the operator to inject the correct binary in any Pod having a supported architecture.
Closes #3868 
Closes #3717

feat: multi-arch in-place update of the operator

---

docs/src/labels_annotations.md

docs: clarify that the `role` label is deprecated

---

pkg/management/postgres/instance.go

fix: major version detection while running pg_rewind

---

config/olm-manifests/bases/cloudnative-pg.clusterserviceversion.yaml
config/olm-samples/kustomization.yaml
config/olm-samples/postgresql_v1_clusterimagecatalog.yaml
config/olm-samples/postgresql_v1_imagecatalog.yaml
tests/e2e/rolling_update_test.go

After merging the image catalogs patch, tests were failing. This patch fixes the OLM scorecard test and the E2E tests (by setting `imageCatalogRef` group).
Closes #4016

test(e2e): fix the pipeline after adding image catalog

---

.wordlist-en-custom.txt
docs/src/security.md

Addressing `PodSecurityPolicy` removal in Kubernetes v1.25. Explaining our reasons for keeping this section for now, even though it's slated for removal in the near future.
Closes #3991

docs: clarify that `PodSecurityPolicy` is now deprecated

---

api/v1/cluster_webhook.go
api/v1/cluster_webhook_test.go

Fix a regression introduced by me at the last minute while changing a string in PR #4020.

fix: unit tests for `wal_level` configuration

---

tests/utils/backup.go

fix the linter issue in release-1.21 branch which caused 
by backport feature https://github.com/cloudnative-pg/cloudnative-pg/pull/3952
Closes:  #4032

fix: fix linter issue in release-1.21 branch

---

controllers/cluster_create.go
controllers/cluster_create_test.go
pkg/reconciler/persistentvolumeclaim/instance.go
pkg/reconciler/persistentvolumeclaim/storagesource.go

Fix bootstrapping error loop by ensuring recovery backups/snapshots
readiness before Cluster construction starts.
This patch addresses an issue where Clusters bootstrapping from
recovery could enter an error loop if the backups or snapshots were
not prepared at the time of cluster creation. It modifies the
bootstrapping process to delay the construction of the first instance
until the necessary recovery backups or snapshots are fully ready,
thus preventing the error loop.
Closes #3654

fix: check recovery backups/snapshots readiness before cluster bootstrap

---

api/v1/cluster_webhook.go
api/v1/cluster_webhook_test.go
docs/src/labels_annotations.md
pkg/management/postgres/configuration.go
pkg/postgres/configuration.go
pkg/utils/labels_annotations.go

Introduce the `cnpg.io/skipWalArchiving` annotation to disable WAL archiving when set to `enabled`.
Closes: #3774

feat: annotation to disable WAL archiving

---

cmd/manager/main.go
internal/cmd/manager/debug/architectures/cmd.go
internal/cmd/manager/debug/cmd.go
tests/e2e/architecture_test.go
tests/utils/operator.go

This patch adds end-to-end (E2E) coverage for the multi-architecture in-place update feature. A debug command was introduced to fetch available architectures in the operator container to facilitate this E2E testing in any environment.
Related To #3840 
Closes #3972

test(e2e): add coverage for multi-arch in-place update

---

api/v1/cluster_webhook.go
api/v1/cluster_webhook_test.go
pkg/reconciler/hibernation/status.go
pkg/reconciler/hibernation/status_test.go
pkg/utils/labels_annotations.go

This patch fix a corner case that during hibernation, instance pod has
been deleted but cluster status still have hibernation condition 
`k8s.enterprisedb.io/hibernation` set to state=false.  Also in this patch, 
we enfored the hibernation annotation `k8s.enterprisedb.io/hibernation` 
can only accept `on` and `off` value in webhook.
closes #3965

fix: cluster phase change should not interrupt the hibernation processing

---

.github/workflows/release-publish.yml

This will allow any user to use the bundle easily without waiting
for this to be published in OperatorHub.io
Closes #4038

feat: publish the OLM bundles in the artifacts directory

---

config/olm-manifests/kustomization.yaml
config/olm-rbac/kustomization.yaml
config/olm-rbac/role_binding_global.yaml
config/olm-rbac/role_global.yaml

Since the fix we applied on #3854 we changed all the `clusterPermissions` section to `permissions` meaning that we also moved the permissions required to get `nodes` and `namespaces` information, which is required by the operator even if is deployed at namespace level.
Closes #3989

fix: add the missing clusterPermissions to OLM deployment

---

docs/src/installation_upgrade.md
docs/src/supported_releases.md

Also mention testing for Kubernetes 1.29
Closes #3747

fix(docs): uncomment section about `--server-side` in upgrades

---

pkg/specs/jobs.go
pkg/specs/pods.go
pkg/specs/volumes.go
pkg/specs/volumes_test.go

This patch aims to reduce memory consumption by using the cluster reference instead of value.

chore: use cluster reference while creating instance volumes

---

controllers/cluster_controller.go
controllers/cluster_restore.go

At present, during the cluster restore from orphan PVCs , it is not possible for the operator to bring back a cluster to a functional state if any orphan pods are present.
This is because the existing pods will linger indefenetly and won't be be recreated with the correct data. To address this issue, this patch ensures that no orphan pods are present during the cluster restore from PVCs by deleting them.

fix: ensure pods with no ownership are deleted during cluster restore

---

config/olm-manifests/bases/cloudnative-pg.clusterserviceversion.yaml

This patch add a group of `features.operators.openshift.io` annotations
to olm bundle.
Closes: #4177

chores: add infrastructure feature annotations to olm bundle

---

.golangci.yml

The configuration option `run.skip-files` is deprecated, now we need to use `issues.exclude-files`
Closes #4183

chore: replace deprecated configuration for golangci-lint

---

pkg/management/barman/restorer/restorer.go

This patch improves the detection of the exit codes coming from `barman-cloud-wal-restore`.

chore: improve `barman-cloud-wal-restore` error detection

---

go.mod

We started to build the operator using Go 1.22 a few weeks ago but we never updated the go.mod file

chore: update Go version in go.mod file

---

pkg/specs/secrets.go
pkg/specs/secrets_test.go

It fixes #4062 
```
kubectl get secret cluster-16-app -o jsonpath="{.data.jdbc-uri}" | base64 -d
jdbc:postgresql://cluster-16-rw.default:5432/app?password=Drg3Zy3AcFC6FzhiiVzpnOEoF8S6rlU7xgqcBkUWHmeTq35GmKmVD5gTNqah4FnZ&user=app
kubectl get secret cluster-16-app -o jsonpath="{.data.uri}" | base64 -d
postgresql://app:Drg3Zy3AcFC6FzhiiVzpnOEoF8S6rlU7xgqcBkUWHmeTq35GmKmVD5gTNqah4FnZ@cluster-16-rw.default:5432/app
```

Change jdbc-uri and uri in app secret

---

go.mod
pkg/management/log/log.go

Since controller-runtime adds their own reconcileID, adding a uuid field is not needed anymore
Closes #2206

chore: remove the UUID from the logs

---

api/v1/cluster_types.go
api/v1/cluster_types_test.go

Within the `GetEnableSuperuserAccess` function, the codebase defaulted to `true` while the `cluster.spec.enableSuperuserAccess` in the CRD was defaulted to `false`.
This discrepancy does not lead to any runtime issues because when the operator retrieves Custom Resources from the API server, the structure has already been populated with the correct values.
However, the problem can still surface during unit tests when utilizing a mock Kubernetes client.
Closes: #4211

fix: align enableSuperuserAccess default

---

.github/renovate.json5

We create one group for the Kubernetes CSI updates, to update all the versions in the same PR
Closes #4229

fix: create renovate group for kubernetes CSI

---

.github/renovate.json5

Previously we were creating a PR for minor and patch version and a different PR for major, this will lead to a temporary failure even in the PR because the major versions will not match, this will create only one PR for update major, minor and patch versions.

fix: renovate should create only one PR for CSI tools

---

hack/setup-cluster.sh

We're going back to use a fixed version of the deployment until we have a release
and we can use the kubernetes-latest path

fix: go back to use a fixed version for the CSI deployment

---

.github/workflows/release-pr.yml
.github/workflows/release-publish.yml

Make the PR release title correct by default.
Make the GH release title correct by default.
Avoid setting the `latest` label in every new GH release.
Set the plain container image as the `latest` tag.
Closes #4160

ci: minor release improvements

---

api/v1/cluster_webhook.go
api/v1/cluster_webhook_test.go
docs/src/postgresql_conf.md
pkg/postgres/configuration.go

Enable setting `wal_log_hints` to `off` for clusters with a single instance.
Previously, `wal_log_hints` was fixed to `on` for every cluster due to `pg_rewind,` which is not required with single-instance clusters.
Closes: #4041

feat: enable configuration of `wal_log_hints`

---

controllers/backup_controller_test.go
controllers/cluster_controller_test.go
controllers/cluster_create_test.go
controllers/cluster_delete_test.go
controllers/cluster_scale_test.go
controllers/cluster_status_test.go
controllers/pooler_controller_test.go
controllers/pooler_predicates_test.go
controllers/pooler_resources_test.go
controllers/pooler_status_test.go
controllers/pooler_update_test.go
controllers/suite_test.go

This patch removes `envtest` from the controller packages. This is done for several reasons:
- is only used in a few of the controller package tests
- acts as a singleton, reducing the predictability of the unit tests
- makes it harder to use the debugger
- does not currently add any real benefit that isn't already covered by webhook unit tests and E2E tests
Note for the reviewers:
In my opinion, `envtest` could be reintroduced  as an integration testing layer with a different PR

test: remove `envtest` from the controller package

---

controllers/cluster_controller.go
controllers/cluster_controller_test.go
controllers/cluster_upgrade.go
controllers/replicas.go

The current code assumes that `updateTargetPrimaryFromPodsPrimaryCluster` is always executed when an HTTP status is present, but this is not the case. This patch ensures that the function concludes with a `noop` instead of an error allowing the reconciliation loop to continue.
Closes #4049

fix: skip updateTargetPrimary if no instance status is available

---

internal/cmd/plugin/maintenance/cmd.go

When we added this regression with PR #3875 when we replaced MaxiumNArgs() function with RequiresArguments() which will actually enforce the number of arguments, but in this case, the maintenance command will work even without arguments just the `-A` flag.
Closes #4263

fix: regression related to the arguments

---

pkg/postgres/lsn.go
pkg/postgres/lsn_test.go
pkg/postgres/status_test.go

`receivedLSN` is empty for instances that have been never attached to streaming replication.
The instance sorting code considers this an error, and the `Less` implementation for LSNs is not antisymmetric, resulting in a non-stable sorting.
This could result in the operator preferring a replica that is never attached to streaming replication over a replica that is more advanced but attached to streaming replication.
Closes: #4284

fix: empty LSN handling in instance sorting

---

controllers/cluster_controller.go
controllers/cluster_upgrade.go

Before switching over to a replica to apply a configuration change of the primary, we now wait for that replica to be connected in streaming replication.
We do that to ensure that the replica has all the data that is written on the primary.
Closes: #4285

fix: wait for elected replica to be in streaming mode before a switchover

---

tests/e2e/asserts_test.go
tests/e2e/fastfailover_test.go

We need to increase the overall timeout since in this platform the test will take longer to run here.
Closes #4306

chore: increase the timeout for failover test on OpenShift

---

internal/cmd/plugin/destroy/cmd.go
internal/cmd/plugin/destroy/destroy.go
internal/cmd/plugin/fence/cmd.go
internal/cmd/plugin/promote/cmd.go

this patch enhance the destroy, fencing and promote plugin command to show
context help if argument number is not met. Also in this patch we make the destroy
command accept both node id and node name as the second parameter. 
Closes: #4266

fix: destroy command show meaningful message if pod not exists

---

pkg/management/postgres/instance.go

After a certificate expires the replicator will start printing error-logs:
```json
{
"level": "info",
"ts": "2024-01-16T11:30:58Z",
"logger": "Replicator",
"msg": "synchronizing replication slots",
"logging_pod": "edge-ha-db-cnpg-3",
"err": "getting replication slot status from primary: failed to connect to `host=edge-ha-db-cnpg-rw user=streaming_replica database=postgres`: failed to write startup message (write failed: x509: certificate has expired or is not yet valid: current time 2024-01-16T11:30:58Z is after 2024-01-16T11:30:45Z)"
}
```
This happens because certificates were read from disk the first time the connection was used and subsequently cached in the pool.
The errors are accompanied by the following error from the leader:
```json
{
"level": "info",
"ts": …
```

fix: reload certificates on configuration update

---

tests/e2e/asserts_test.go
tests/e2e/backup_restore_test.go
tests/utils/minio.go

test(e2e): more precise wildcard to match wal file

---

docs/src/connection_pooling.md

This patch aims to fix a typo in our documentation that fails the spellcheck step.

chore: correct typo in the documentation

---

pkg/certs/k8s.go

Increase the timeout the operator waits for the Kubelet to
refresh a mounted secret from ~10 to ~60 sec to better cope with
busy Kubernetes clusters.
This timeout is used during certificate maintenance and when it expires
the operator will retry after the configured time (default one day).
Closes:  #4075

chore: increase waiting for a mounted secret timeout

---

internal/cmd/plugin/destroy/destroy.go
internal/cmd/plugin/hibernate/on.go

This patch fix the e2e failed caused by patch  https://github.com/cloudnative-pg/cloudnative-pg/pull/4280
Closes: #4329

fix: use full instance name for the destroy method

---

internal/cnpi/plugin/operatorclient/client.go

Previously we were patching the object even if this didn't change, this was triggering a patch over an object that was already patched and deleted.
Closes #4301

fix: do not patch when object doesn't change

---

internal/cmd/manager/instance/restore/cmd.go
pkg/fileutils/fileutils.go
pkg/fileutils/fileutils_test.go
pkg/management/barman/capabilities/detect.go
pkg/management/barman/capabilities/detect_test.go
pkg/management/barman/capabilities/type.go
pkg/management/barman/errors.go
pkg/management/postgres/backup_test.go
pkg/management/postgres/restore.go

This patch clean up the pgdata directory if barman-cloud-restore is failed due
to network error or general error, so the next restore job can retry the restore work.
Closes: #4150

feat: cleanup pgdata directory if restore job failed

---

Makefile

Any `make` command currently returns the following error:
```
fatal: Not a valid object name ^
```
Closes #4317

chore: fix makefile nested command

---

.github/workflows/continuous-delivery.yml
.github/workflows/continuous-integration.yml
.github/workflows/release-publish.yml
Makefile

We must always add to the CONTROLLER_IMG variable the words `catalog` and
`bundle` otherwise, we can't have the TAG if the CONTROLLER_IMG was already
provided by the user.

fix: regression on the creation of the bundle and catalog for OLM

---

internal/cmd/plugin/logical/subscription/syncsequences/get.go

Fix the `kubectl-cnpg subscription sync-sequences` execution when the source or the destination database has no sequence.
Previously, the command was failing with the following error:
Error: while getting sequences status from the source database: while decoding JSON output: unexpected end of JSON input
Closes #4345

fix(plugin): handle empty response in sync-sequences plugin command

---

docs/src/image_catalog.md
docs/src/rolling_update.md

Provide instructions on how to update the `ClusterImageCatalog` resources for PostgreSQL and PostGIS images supported by the Community.
Closes #4320

docs: `ClusterImageCatalog` for `postgresql` and `postgis` images

---

config/manager/default-monitoring.yaml

PostgreSQL 17 removed some columns from `pg_stat_bgwriter`, moving them to the new `pg_stat_checkpointer` view. This patch disables the gathering of `pg_stat_bgwriter`
metrics in PostgreSQL v17+. A further patch will add support for the new format.
Workaround for #3411

fix: disable metrics from `pg_stat_bgwriter` in v17+
